Repository qgis/QGIS-Documentation, pull requests merged in 2019-03, with the labels that each got.

#3502 [Processing] geodesic split lines algorithm
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
  source/substitutions.txt
Labels: Processing help

#3524 Remove C++ API links from Authentication chapter
  source/docs/pyqgis_developer_cookbook/authentication.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3442 Add more information and cross links to algorithms
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.4

#3531 Fix wrong indentation of the list
  source/docs/pyqgis_developer_cookbook/loadlayer.rst
Labels: backport release_3.4

#3516 N m relations
  source/docs/user_manual/working_with_vector/attribute_table.rst
  source/docs/user_manual/working_with_vector/img/relations6.png
  source/docs/user_manual/working_with_vector/img/relations7.png
  source/docs/user_manual/working_with_vector/img/relations8.png
Labels: backport release_3.4

#3453 Review some distance analysis algorithms
  source/docs/user_manual/processing_algs/qgis/img/distance_hub.png
  source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Labels: backport release_3.4

#3517 add example how to make a Processing plugin
  source/docs/pyqgis_developer_cookbook/processing.rst
Labels: backport release_3.4

#3498 Reports - Adding the contents to "how to make a report"
  source/docs/user_manual/print_composer/create_reports.rst
  source/docs/user_manual/print_composer/img/add_section.png
  source/docs/user_manual/print_composer/img/edit_group_body.png
  source/docs/user_manual/print_composer/img/export_options_reports.png
  source/docs/user_manual/print_composer/img/field_group.png
  source/docs/user_manual/print_composer/img/footer.png
  source/docs/user_manual/print_composer/img/header.png
  source/docs/user_manual/print_composer/img/headerfooter.png
  source/docs/user_manual/print_composer/img/ports.png
  source/docs/user_manual/print_composer/img/project-1.png
  source/docs/user_manual/print_composer/img/report-2.png
  source/docs/user_manual/print_composer/img/report1.png
  source/docs/user_manual/print_composer/img/report3.png
  source/docs/user_manual/print_composer/img/report4.png
  source/docs/user_manual/print_composer/img/report5.png
  source/docs/user_manual/print_composer/img/report_consec.png
  source/docs/user_manual/print_composer/img/report_flex.png
  source/docs/user_manual/print_composer/img/report_header.png
  source/docs/user_manual/print_composer/img/subsection.png
  source/docs/user_manual/print_composer/index.rst
Labels: backport release_3.4

#3532 Add option to save/load project to PostgreSQL
  source/docs/user_manual/introduction/getting_started.rst
  source/docs/user_manual/introduction/qgis_gui.rst
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.4

#3546 Code testing guidelines added
  source/docs/documentation_guidelines/cookbook_guidelines.rst
  source/docs/documentation_guidelines/index.rst
Labels: backport release_3.4

#3560 Fix indentation of code frame
  source/docs/pyqgis_developer_cookbook/geometry.rst
Labels: backport release_3.4

#3564 Review of the Processing contribution guidelines
  source/docs/documentation_guidelines/writing.rst
  source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Labels: Guidelines, Processing help, backport release_3.4

#3562 Introducing mesh layers
  source/docs/documentation_guidelines/substitutions.rst
  source/docs/user_manual/index.rst
  source/docs/user_manual/working_with_mesh/img/mesh_datasource_manager.png
  source/docs/user_manual/working_with_mesh/img/mesh_grid_types.png
  source/docs/user_manual/working_with_mesh/img/mesh_info_properties.png
  source/docs/user_manual/working_with_mesh/img/mesh_visualisation.png
  source/docs/user_manual/working_with_mesh/img/triangual_grid_with_numered_vertices.png
  source/docs/user_manual/working_with_mesh/index.rst
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
  source/substitutions.txt
  static/common/mActionAddMeshLayer.png
Labels: User Manual, needs-forward-porting

#3481 Organize sections
  source/docs/pyqgis_developer_cookbook/vector.rst
Labels: backport release_3.4

#3344 Update grass_setup.rst
  source/docs/training_manual/grass/grass_setup.rst
Labels: backport release_3.4

#3479 default startup.py location hint
  source/docs/pyqgis_developer_cookbook/intro.rst
Labels: backport release_3.4

#3578 Review the digitizing "Rotate feature(s)" tool
  source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: User Manual, backport release_3.4

#3555 Improvements to PyQGIS code testing guidelines
  source/docs/documentation_guidelines/cookbook_guidelines.rst
Labels: backport release_3.4, enhancement

#3581 Remove the |browseButton| substitution
  source/docs/documentation_guidelines/substitutions.rst
  source/docs/training_manual/complete_analysis/analysis_exercise.rst
  source/docs/training_manual/rasters/data_manipulation.rst
  source/docs/training_manual/rasters/terrain_analysis.rst
  source/docs/training_manual/vector_analysis/basic_analysis.rst
  source/docs/training_manual/vector_analysis/network_analysis.rst
  source/docs/user_manual/introduction/general_tools.rst
  source/docs/user_manual/introduction/qgis_configuration.rst
  source/docs/user_manual/managing_data_source/create_layers.rst
  source/docs/user_manual/preamble/conventions.rst
  source/docs/user_manual/print_composer/composer_items/composer_html_frame.rst
  source/docs/user_manual/print_composer/composer_items/composer_image.rst
  source/docs/user_manual/processing/batch.rst
  source/docs/user_manual/processing/toolbox.rst
  source/substitutions.txt
  static/common/browsebutton.png
Labels: Text, backport release_3.4

#3571 Code update in console.rst
  source/docs/user_manual/processing/console.rst
Labels: Processing, User Manual, backport release_3.4

#3593 Fix typo
  source/docs/pyqgis_developer_cookbook/canvas.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3585 Update modeler.rst to mention that models will show up in the browser
  source/docs/user_manual/processing/modeler.rst
Labels: backport release_3.4

#3586 Update general_tools.rst to mention Layer Definition Files.
  source/docs/user_manual/introduction/general_tools.rst
  source/docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.4

#3572 Improve Mesh layer description v2
  source/docs/user_manual/working_with_mesh/img/mesh_groups.png
  source/docs/user_manual/working_with_mesh/img/mesh_symbology.png
  source/docs/user_manual/working_with_mesh/img/mesh_symbology_contours.png
  source/docs/user_manual/working_with_mesh/img/mesh_symbology_grid.png
  source/docs/user_manual/working_with_mesh/img/mesh_symbology_vector.png
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
  static/common/contours_active.png
  static/common/contours_inactive.png
  static/common/mesh_groups_explore.png
  static/common/mesh_rendering.png
  static/common/vector_active.png
  static/common/vector_inactive.png
Labels: backport release_3.4

#3544 Update Pycookbook CRS section and add tests
  source/docs/pyqgis_developer_cookbook/crs.rst
Labels: backport release_3.4
