Repository qgis/QGIS-Documentation, pull requests merged in 2019-04, with the labels that each got.

#3622 Clarifies when the testoutput is mandatory
  source/docs/documentation_guidelines/cookbook_guidelines.rst
Labels: backport release_3.4

#3625 Add missing local TOC
  source/docs/documentation_guidelines/cookbook_guidelines.rst
Labels: backport release_3.4

#3626 Add direct link to locator bar description
  source/docs/user_manual/introduction/qgis_configuration.rst
  source/docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.4

#3403 Update scripts.rst
  source/docs/user_manual/processing/img/script_online.png
  source/docs/user_manual/processing/scripts.rst
Labels: Processing, User Manual, needs-backport

#3616 Remove mention of obsolete use of |updatedisclaimer
  source/docs/documentation_guidelines/do_translations.rst
Labels: Guidelines, backport release_3.4

#3643 simplify python expression snippet
  source/docs/pyqgis_developer_cookbook/expressions.rst
Labels: backport release_3.4

#3660 Add some hyperlinks to qgstask api features
  source/docs/pyqgis_developer_cookbook/tasks.rst
Labels: backport release_3.4

#3659 Some rendering fixes
  source/docs/pyqgis_developer_cookbook/geometry.rst
Labels: backport release_3.4

#3658 Remove obsolete warning
  source/docs/pyqgis_developer_cookbook/expressions.rst
  source/docs/pyqgis_developer_cookbook/vector.rst
Labels: backport release_3.4

#3673 Changed download link
  source/docs/training_manual/forestry/basic_lidar.rst
Labels: backport release_3.4

#3677 Error in format page
  source/docs/user_manual/auth_system/auth_overview.rst
Labels: backport release_3.4

#3680 Remove "sudo" ? ** NOT SURE ABOUT THIS! **
  source/docs/training_manual/qgis_server/install.rst
Labels: backport release_3.4

#3682 Rewording "Project Properties" to "Properties" and removing icon
  source/docs/user_manual/working_with_projections/working_with_projections.rst
Labels: backport release_3.4

#3482 vertex tool updates in 3.4 and 3.6 #3450
  source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
  source/docs/user_manual/working_with_vector/img/select_vertex_snap_to_grid.png
  source/docs/user_manual/working_with_vector/img/vertex_snap_to_grid.png
Labels: backport release_3.4

#3683 Superfluous colon
  source/docs/user_manual/print_composer/create_reports.rst
Labels: backport release_3.4

#3679 first 3 chapters updates, minor updates, mainly screenshots
  source/docs/training_manual/processing/img/set_up/installer.png
  source/docs/training_manual/processing/img/set_up/menu.png
  source/docs/training_manual/processing/img/set_up/toolbox.png
  source/docs/training_manual/processing/img/set_up/toolbox_advanced.png
  source/docs/training_manual/processing/img/warning/kriging.png
  source/docs/training_manual/processing/intro.rst
  source/docs/training_manual/processing/set_up.rst
  source/docs/training_manual/processing/warning.rst
Labels: Training Manual, backport release_3.4

#3642 add environment variable for QGIS startup, deploying QGIS in an organization
  source/docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.4

#3687 Clean the pyqgis nitpick list from conf.py file
  source/conf.py
  source/docs/pyqgis_developer_cookbook/composer.rst
  source/docs/pyqgis_developer_cookbook/crs.rst
  source/docs/pyqgis_developer_cookbook/intro.rst
  source/docs/pyqgis_developer_cookbook/loadlayer.rst
  source/docs/pyqgis_developer_cookbook/loadproject.rst
  source/docs/pyqgis_developer_cookbook/network_analysis.rst
  source/docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
  source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
  source/docs/pyqgis_developer_cookbook/raster.rst
  source/docs/pyqgis_developer_cookbook/server.rst
  source/docs/pyqgis_developer_cookbook/vector.rst
  source/docs/user_manual/preamble/features.rst
Labels: backport release_3.4

#3705 Digitizing snap to grid
  source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.4
