Repository qgis/QGIS-Documentation, pull requests merged in 2019-06, with the labels that each got.

#3621 PyQGIS Cook book: Add NEW section "Cheat sheet.rst"
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
  source/docs/pyqgis_developer_cookbook/index.rst
Labels: backport release_3.4, squash!

#3785 Add details on new project crs and update CRS dialogs screenshots
  source/docs/user_manual/introduction/qgis_configuration.rst
  source/docs/user_manual/working_with_projections/img/crsdialog.png
  source/docs/user_manual/working_with_projections/img/projectionDialog.png
Labels: backport release_3.4

#3783 Update wms.rst to reflect 3.4 CRS behaviour
  source/docs/training_manual/online_resources/img/enable_projection.png
  source/docs/training_manual/online_resources/wms.rst
Labels: backport release_3.4

#3743 Rework the QGIS Server Apache section
  source/docs/user_manual/working_with_ogc/server/getting_started.rst
Labels: backport release_3.4

#3795 Display label for cheat sheet sources instead of url
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3798 Wrongfully mentioned menu entry
  source/docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.4

#3797 Missing colon
  source/docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.4

#3774 Backports PyQGIS cheat sheet
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
  source/docs/pyqgis_developer_cookbook/index.rst
Labels: PyQGIS Cookbook

#3792 [pyqgis] Fix reorder index QGIS Cheat sheet
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3770 Improve readability
  source/docs/user_manual/processing/scripts.rst
Labels: backport release_3.4

#3794 [pyqgis] tests added for geometry chapter
  source/docs/pyqgis_developer_cookbook/geometry.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3805 Move german screenshots of heatmap
  source/docs/user_manual/processing_algs/qgis/img/de/heatmap_dialog.png
  source/docs/user_manual/processing_algs/qgis/img/de/heatmap_loaded_colour.png
  source/docs/user_manual/processing_algs/qgis/img/de/heatmap_loaded_grey.png
  source/docs/user_manual/processing_algs/qgis/img/de/heatmap_start.png
Labels: backport release_3.4

#3804 Remove some old or unused images
  source/docs/user_manual/managing_data_source/img/fr/shapefileopendialog.png
  source/docs/user_manual/plugins/img/de/dxf2shape_dialog.png
  source/docs/user_manual/plugins/img/de/interpolate_dialog.png
  source/docs/user_manual/plugins/img/de/oracle_create_dialog.png
  source/docs/user_manual/plugins/img/de/raster_terrain_dialog.png
  source/docs/user_manual/working_with_vector/img/vertex_editor_panel_contextual_button.png
Labels: backport release_3.4

#3813 Double wording "the"
  source/docs/pyqgis_developer_cookbook/vector.rst
Labels: backport release_3.4

#3667 Update working_with_projections.rst
  source/docs/user_manual/working_with_projections/img/nadgrids_example.PNG
  source/docs/user_manual/working_with_projections/working_with_projections.rst
Labels: backport release_3.4

#3731 Structure Core plugins chapter
  source/docs/user_manual/plugins/core_plugins/img/check_geometries.png
  source/docs/user_manual/plugins/core_plugins/img/choose_points.png
  source/docs/user_manual/plugins/core_plugins/img/coordinate_capture_dialog.png
  source/docs/user_manual/plugins/core_plugins/img/create_offline_project.png
  source/docs/user_manual/plugins/core_plugins/img/db_manager.png
  source/docs/user_manual/plugins/core_plugins/img/db_manager_sql.png
  source/docs/user_manual/plugins/core_plugins/img/de/check_geometries.png
  source/docs/user_manual/plugins/core_plugins/img/de/choose_points.png
  source/docs/user_manual/plugins/core_plugins/img/de/coordinate_capture_dialog.png
  source/docs/user_manual/plugins/core_plugins/img/de/create_offline_project.png
  source/docs/user_manual/plugins/core_plugins/img/de/db_manager.png
  source/docs/user_manual/plugins/core_plugins/img/de/georefplugin.png
  source/docs/user_manual/plugins/core_plugins/img/de/metasearch-record-metadata.png
  source/docs/user_manual/plugins/core_plugins/img/de/metasearch-search.png
  source/docs/user_manual/plugins/core_plugins/img/de/metasearch-services.png
  source/docs/user_manual/plugins/core_plugins/img/de/metasearch-settings.png
  source/docs/user_manual/plugins/core_plugins/img/de/raster_menu.png
  source/docs/user_manual/plugins/core_plugins/img/de/topology_checker.png
  source/docs/user_manual/plugins/core_plugins/img/de/transformation_settings.png
  source/docs/user_manual/plugins/core_plugins/img/evisdatabase.png
  source/docs/user_manual/plugins/core_plugins/img/evisdisplay.png
  source/docs/user_manual/plugins/core_plugins/img/evisexternal.png
  source/docs/user_manual/plugins/core_plugins/img/evisoptions.png
  source/docs/user_manual/plugins/core_plugins/img/evispredefined.png
  source/docs/user_manual/plugins/core_plugins/img/evissql_query.png
  source/docs/user_manual/plugins/core_plugins/img/geometry_checker.svg
  source/docs/user_manual/plugins/core_plugins/img/geometry_checker_scheme.png
  source/docs/user_manual/plugins/core_plugins/img/georefplugin.png
  source/docs/user_manual/plugins/core_plugins/img/metasearch-record-metadata.png
  source/docs/user_manual/plugins/core_plugins/img/metasearch-search.png
  source/docs/user_manual/plugins/core_plugins/img/metasearch-services.png
  source/docs/user_manual/plugins/core_plugins/img/metasearch-settings.png
  source/docs/user_manual/plugins/core_plugins/img/metasearch-splash.png
  source/docs/user_manual/plugins/core_plugins/img/raster_menu.png
  source/docs/user_manual/plugins/core_plugins/img/topology_checker.png
  source/docs/user_manual/plugins/core_plugins/img/transformation_settings.png
  source/docs/user_manual/plugins/core_plugins/index.rst
  source/docs/user_manual/plugins/core_plugins/plugins_coordinate_capture.rst
  source/docs/user_manual/plugins/core_plugins/plugins_db_manager.rst
  source/docs/user_manual/plugins/core_plugins/plugins_evis.rst
  source/docs/user_manual/plugins/core_plugins/plugins_geometry_checker.rst
  source/docs/user_manual/plugins/core_plugins/plugins_georeferencer.rst
  source/docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
  source/docs/user_manual/plugins/core_plugins/plugins_offline_editing.rst
  source/docs/user_manual/plugins/core_plugins/plugins_topology_checker.rst
  source/docs/user_manual/plugins/index.rst
Labels: backport release_3.4

#3824 Update ntv2 screenshot and do some cosmetic
  source/docs/user_manual/working_with_projections/img/nadgrids_example.PNG
  source/docs/user_manual/working_with_projections/working_with_projections.rst
Labels: backport release_3.4

#3811 [pyqgis] Add new snippets QGIS Cheat sheet
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3806 Move the Python Console chapter after the Core Plugins
  source/docs/user_manual/plugins/index.rst
Labels: backport release_3.4

#3821 [TM] Update the WMS lesson with screenshots and using numbered list
  source/docs/training_manual/online_resources/img/datasourcemanager_wms.png
  source/docs/training_manual/online_resources/img/enable_projection.png
  source/docs/training_manual/online_resources/img/new_connection_listed.png
  source/docs/training_manual/online_resources/img/new_map.png
  source/docs/training_manual/online_resources/img/new_wms_connection.png
  source/docs/training_manual/online_resources/img/new_wms_entries.png
  source/docs/training_manual/online_resources/img/osm_wms_selected.png
  source/docs/training_manual/online_resources/img/pseudo_mercator_selected.png
  source/docs/training_manual/online_resources/img/reprojection_off.png
  source/docs/training_manual/online_resources/img/wms_result.png
  source/docs/training_manual/online_resources/wms.rst
Labels: Training Manual, backport release_3.4

#3755 More details on GDAL create options
  source/docs/user_manual/introduction/img/gdalCreateOptions.png
  source/docs/user_manual/introduction/img/gdalPyramidsOptions.png
  source/docs/user_manual/introduction/qgis_configuration.rst
  source/docs/user_manual/managing_data_source/create_layers.rst
Labels: backport release_3.4

#3752 Update create new vector to match 3.6
  source/docs/training_manual/create_vector_data/create_new_vector.rst
Labels: backport release_3.4

#3836 fixing edit creation options in raster miscellaneous to align with #3755
  source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Labels: backport release_3.4

#3838 Homogenize raster "additional creation options"
  source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
  source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
  source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
  source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
Labels: backport release_3.4

#3769 Add example on aggregate expression
  source/docs/pyqgis_developer_cookbook/expressions.rst
Labels: backport release_3.4, squash!

#3842 Typo
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
Labels: backport release_3.4

#3822 Move the step-by-step chapter to the beginning of documentation
  source/docs/documentation_guidelines/first_contribution.rst
  source/docs/documentation_guidelines/index.rst
  source/docs/documentation_guidelines/writing.rst
Labels: Guidelines, backport release_3.4

#3847 Update qgis_configuration.rst
  source/docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.4

#3853 Typo
  source/docs/user_manual/introduction/general_tools.rst
Labels: backport release_3.4

#3855 Add/organize introductions to guidelines chapters
  source/docs/documentation_guidelines/first_contribution.rst
  source/docs/documentation_guidelines/index.rst
  source/docs/documentation_guidelines/writing.rst
Labels: Guidelines, backport release_3.4

#3869 Isolate expressions tests in a group
  source/docs/documentation_guidelines/cookbook_guidelines.rst
  source/docs/pyqgis_developer_cookbook/expressions.rst
Labels: High Priority, PyQGIS Cookbook, backport release_3.4, bug

#3820 review code snippet
  source/docs/pyqgis_developer_cookbook/plugins/snippets.rst
Labels: PyQGIS Cookbook, backport release_3.4

#3764 Fixes example for "Use Filter, Opacities and Filter parameters"
  source/docs/training_manual/qgis_server/wms.rst
Labels: backport release_3.4

#3892 Update scripts.rst
  source/docs/user_manual/processing/scripts.rst
Labels: User Manual

#3897 Adds doctest_global_cleanup to clear QgsProject instance
  source/conf.py
  source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: backport release_3.4

#3904 Some cosmetics
  source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
Labels: backport release_3.4

#3883 Place the GIS Intro and training manual at the first place in TOC
  source/docs/index.rst
Labels: backport release_3.4

#3868 Improve the discovery of the command line options
  source/docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.4

#3818 Cosmetic rendering
  source/docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.4
