Repository qgis/QGIS-Documentation, pull requests merged in 2019-05, with the labels that each got.

#3480 Add missing file format
  source/docs/pyqgis_developer_cookbook/vector.rst
Labels: backport release_3.4

#3449 Add some tips for expression dialog
  source/docs/user_manual/working_with_vector/attribute_table.rst
  source/docs/user_manual/working_with_vector/expression.rst
  source/docs/user_manual/working_with_vector/img/customFunction.png
  source/docs/user_manual/working_with_vector/img/fieldcalculator.png
  source/docs/user_manual/working_with_vector/img/function_list.png
Labels: backport release_3.4

#3727 Modifies wrong path for startup.py initialization file.
  source/docs/pyqgis_developer_cookbook/intro.rst
Labels: backport release_3.4

#3747 [tm] Switch to numbered list, aerate and make screenshots more legible
  source/docs/training_manual/vector_analysis/network_analysis.rst
Labels: backport release_3.4

#3744 Adding optional tag and new parameters to GDAL miscellaneous algs #3287
  source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Labels: backport release_3.4

#3721 Fixes SVG customization example
  source/docs/user_manual/working_with_vector/style_library.rst
Labels: backport release_3.4

#3726 Add more PyQGIS links
  source/docs/user_manual/processing/console.rst
Labels: User Manual, backport release_3.4

#3745 Fixing indentation
  source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
  source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
Labels: backport release_3.4

#3754 Update and complete Gdal warp algorithm description
  source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
Labels: Processing Alg, backport release_3.4

#3753 Tweak the @parent variable description
  source/docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.4

#3759 Update and complete GDAL Warp algorithm description
  source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
Labels: Processing Alg

#3617 Adds python plugin folder to env file
  venv.mk
Labels: Processing, PyQGIS Cookbook, backport release_3.4
