Repository qgis/QGIS-Documentation, pull requests merged in 2020-05, with the labels that each got.

#5379 Update the QGIS raster analysis algorithms - table for parameters
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: backport release_3.10

#5403 Layout user doc
  docs/user_manual/print_composer/overview_composer.rst
Labels: User Manual, backport release_3.10, backport release_3.4

#5393 Minor: Tracing tool is in the Snapping toolbar
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.10

#5377 Doc fuzzy gaussian
  docs/user_manual/processing_algs/qgis/img/gaussianformula.png
  docs/user_manual/processing_algs/qgis/img/gaussianimage.png
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: Processing Alg

#5427 Layout doc
  docs/user_manual/print_composer/composer_items/composer_items_options.rst
Labels: User Manual, backport release_3.10, backport release_3.4

#5432 Upgrade training manual iterative execution to QGIS 3 models
  docs/training_manual/processing/img/iterative_model/model.png
  docs/training_manual/processing/img/iterative_model/model2.png
  docs/training_manual/processing/iterative_model.rst
Labels: backport release_3.10, backport release_3.4

#5435 SAGA can only be run if it is shipped with QGIS
  docs/user_manual/processing/3rdParty.rst
Labels: 3.0, backport release_3.10, backport release_3.4

#5430 Fix backslash escaping in 3rdParty.rst
  docs/user_manual/processing/3rdParty.rst
Labels: backport release_3.10, backport release_3.4

#4891 Document Shape Digitizing tools
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
  qgis-projects/user_manual/working_with_vector_02.qgs
Labels: backport release_3.10, backport release_3.4

#5456 Fix error (wrong layer) in Working with vector data (training manual)
  docs/training_manual/basic_map/vector_data.rst
Labels: backport release_3.10, backport release_3.4

#5236 Open third-party urls of the bottom bar in a new tab
  themes/rtd_qgis/versions.html
Labels: backport release_3.10, backport release_3.4

#5321 Add details on 3D terrain types
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5451 Add expression functions available in layout legend item
  docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.10

#5469 Double wording "the"
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
Labels: backport release_3.10, backport release_3.4

#5461 TM: Update the supplementary exercise to use the training manual data
  docs/training_manual/complete_analysis/analysis_exercise.rst
Labels: backport release_3.10, backport release_3.4

#5476 Corrected typo's
  docs/user_manual/print_composer/create_reports.rst
Labels: backport release_3.10, backport release_3.4

#5493 Fix language's name
  docs/user_manual/preamble/contributors.rst
Labels: backport release_3.10

#5511 Typo fixes
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.10

#5385 Load PostGIS raster using manual URI string.
  docs/pyqgis_developer_cookbook/loadlayer.rst
Labels: PyQGIS Cookbook

#5507 Various improvements to GUI items lists
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5378 Update vector.rst
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook

#5324 Include processing algorithms and expression functions as possible uses of Python
  docs/pyqgis_developer_cookbook/intro.rst
Labels: PyQGIS Cookbook, backport release_3.10

#5297 Various fixes to the authentication chapter in cookbook
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/user_manual/auth_system/auth_overview.rst
Labels: backport release_3.10

#5536 Fix paste to temporary scratch layer shortcut
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5538 Tools to load layers are on the "Manage layers" toolbar
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5541 Substitution cleanup
  docs/pyqgis_developer_cookbook/plugins/pluginlayer.rst
  docs/pyqgis_developer_cookbook/plugins/releasing.rst
  docs/pyqgis_developer_cookbook/server.rst
  docs/training_manual/vector_classification/label_tool.rst
  static/common/mIconImport.gif
  substitutions.txt
Labels: backport release_3.10

#5537 Refer to the "Selection toolbar" for selection tools
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/qgis_gui.rst
Labels: 3.14

#5549 Make buffer algorithm images clickable and background transparent
  docs/user_manual/processing_algs/qgis/img/buffer.png
  docs/user_manual/processing_algs/qgis/img/buffer_cap_style.png
  docs/user_manual/processing_algs/qgis/img/buffer_dissolve.png
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.10, backport release_3.4

#5420 rename Graphics to Plots (fix #5419)
  docs/user_manual/processing_algs/qgis/index.rst
  docs/user_manual/processing_algs/qgis/plots.rst
Labels: 3.14, Processing Alg, User Manual

#5548 Move notions' index from training manual to main repo first page
  docs/index.rst
  docs/training_manual/index.rst
Labels: backport release_3.10

#5220 List all the released versions of docs
  docs_conf.yml
Labels: backport release_3.10, backport release_3.4

#5169 Update QGIS BugTracker link
  docs/user_manual/preamble/help_and_support.rst
Labels: backport release_3.10

#5568 Rewording caption image Position and Size
  docs/user_manual/print_composer/composer_items/composer_items_options.rst
Labels: backport release_3.10, backport release_3.4

#5573 Fix wrong link in projection
  docs/user_manual/working_with_projections/working_with_projections.rst
Labels: backport release_3.10, backport release_3.4

#5578 Workaround segfault in auth manager test code
  docs/user_manual/auth_system/auth_workflows.rst
Labels: Code, backport release_3.10

#5579 Wrong name new mapset
  docs/user_manual/grass_integration/grass_integration.rst
Labels: backport release_3.10, backport release_3.4
