Repository qgis/QGIS-Documentation, pull requests merged in 2020-06, with the labels that each got.

#5581 Use include to add a Python code section to all processing algorithms
  docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: Code, IN PROGRESS, Processing Alg, User Manual, backport release_3.10, enhancement

#5591 Missing format table for output
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: backport release_3.10

#5598 Add code include for QGIS raster analysis algorithms
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: backport release_3.10

#5584 Move the categories contextual menu under category section
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/working_with_vector/vector_properties.rst
  static/common/mActionToggleAllLayers.png
  substitutions.txt
Labels: backport release_3.10

#5224 Update list of panels
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5600 Remove trailing spaces - QGIS Raster analysis algs
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: 3.10

#5612 Change to SpatiaLite
  docs/training_manual/databases/db_manager.rst
  docs/training_manual/databases/index.rst
  docs/training_manual/databases/spatialite.rst
Labels: backport release_3.10, backport release_3.4

#5622 Add code section to QGIS cartography algs
  docs/user_manual/processing_algs/qgis/cartography.rst
Labels: backport release_3.10

#5626 Add code section to QGIS file tools algs
  docs/user_manual/processing_algs/qgis/filetools.rst
Labels: backport release_3.10

#5629 Add code section to QGIS plot algs
  docs/user_manual/processing_algs/qgis/plots.rst
Labels: backport release_3.10

#5632 Add code section to QGIS layer tools algs
  docs/user_manual/processing_algs/qgis/layertools.rst
Labels: backport release_3.10

#5634 Add code section to QGIS modeller tools algs
  docs/user_manual/processing_algs/qgis/modelertools.rst
Labels: backport release_3.10

#5637 Add code section to QGIS network analysis algs
  docs/user_manual/processing_algs/qgis/networkanalysis.rst
Labels: backport release_3.10

#5638 Add code section to QGIS raster terrain analysis algs
  docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
Labels: backport release_3.10

#5640 Add code section to QGIS raster tools algs
  docs/user_manual/processing_algs/qgis/rastertools.rst
Labels: backport release_3.10

#5643 Add code section to QGIS vector analysis algs
  docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Labels: backport release_3.10

#5646 Add code section to QGIS vector general algs
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: backport release_3.10

#5648 Add code section to QGIS vector overlay algs
  docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Labels: backport release_3.10

#5650 Add code section to QGIS vector selection algs
  docs/user_manual/processing_algs/qgis/vectorselection.rst
Labels: backport release_3.10

#5652 Add code section to QGIS vector table algs
  docs/user_manual/processing_algs/qgis/vectortable.rst
Labels: backport release_3.10

#5659 Add code section to lastools algs
  docs/user_manual/processing_algs/lidartools/lastools.rst
Labels: backport release_3.10

#5483 ctrl-click - group checkbox
  docs/user_manual/introduction/general_tools.rst
Labels: backport release_3.10

#5666 Another try to fix the canonical URL
  conf.py
Labels: backport release_3.10

#5669 Update the TM Using Print Layout lesson to QGIS 3
  docs/training_manual/map_composer/img/align_center_dropdown.png
  docs/training_manual/map_composer/img/categories_reordered.png
  docs/training_manual/map_composer/img/drag_add_map.png
  docs/training_manual/map_composer/img/legend_added.png
  docs/training_manual/map_composer/img/map_composer_result.png
  docs/training_manual/map_composer/img/move_map.png
  docs/training_manual/map_composer/img/print_composer_dialog.png
  docs/training_manual/map_composer/img/resize_map.png
  docs/training_manual/map_composer/img/title_font_alignment.png
  docs/training_manual/map_composer/map_composer.rst
Labels: backport release_3.10

#5672 Adjusting a few too long lines (clean-up after #5669)
  docs/training_manual/map_composer/map_composer.rst
Labels: backport release_3.10

#5675 Tm cartography 431
  docs/training_manual/vector_classification/classification.rst
  docs/training_manual/vector_classification/img/add_area_column.png
  docs/training_manual/vector_classification/img/bad_landuse_labels.png
  docs/training_manual/vector_classification/img/categories_explained.png
  docs/training_manual/vector_classification/img/categorisation_result.png
  docs/training_manual/vector_classification/img/categorised_style_settings.png
  docs/training_manual/vector_classification/img/categorised_styles.png
  docs/training_manual/vector_classification/img/change_layer_color.png
  docs/training_manual/vector_classification/img/empty_category.png
Labels: backport release_3.10

#5547 Add more information about the form view of attribute tables
  docs/user_manual/working_with_vector/attribute_table.rst
  docs/user_manual/working_with_vector/img/attribute_table_views.png
Labels: Screenshots, Text, User Manual, backport release_3.10, enhancement

#5684 TM - Update snapping options screenshot
  docs/training_manual/create_vector_data/img/set_snapping_options.png
  docs/training_manual/create_vector_data/topo_editing.rst
Labels: backport release_3.10

#5687 Indicate how to enable Processing
  docs/user_manual/processing/intro.rst
Labels: backport release_3.10

#5692 Third party section - spell checking and adding index entries
  docs/user_manual/appendices/qgis_r_syntax.rst
  docs/user_manual/processing/3rdParty.rst
Labels: backport release_3.10

#5619 Make links to Sample Dataset consistent in testing docs
  docs/user_manual/introduction/getting_started.rst
Labels: backport release_3.10

#5697 Update the TM Actions lesson
  docs/training_manual/create_vector_data/actions.rst
  docs/training_manual/create_vector_data/img/add_new_column.png
  docs/training_manual/create_vector_data/img/column_settings.png
  docs/training_manual/create_vector_data/img/google_search_action.png
  docs/training_manual/create_vector_data/img/layer_actions.png
  docs/training_manual/create_vector_data/img/python_action_example.png
  docs/training_manual/create_vector_data/img/run_feature_action_select.png
  docs/training_manual/create_vector_data/img/school_property_no_image.png
  docs/training_manual/create_vector_data/img/select_file_name.png
  docs/training_manual/create_vector_data/img/select_image.png
  docs/training_manual/create_vector_data/img/show_image_action.png
  docs/training_manual/create_vector_data/img/toggle_editing_mode.png
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5706 Update the TM 3.2 symbology lesson
  docs/training_manual/basic_map/img/add_symbol_layer_button.png
  docs/training_manual/basic_map/img/change_to_marker_line.png
  docs/training_manual/basic_map/img/correct_symbol_layers.png
  docs/training_manual/basic_map/img/geometry_generator.png
  docs/training_manual/basic_map/img/geometry_generator_query.png
  docs/training_manual/basic_map/img/layer_properties_style.png
  docs/training_manual/basic_map/img/marker_line_interval.png
  docs/training_manual/basic_map/img/marker_type_dropdown.png
  docs/training_manual/basic_map/img/multiple_symbol_layers.png
  docs/training_manual/basic_map/img/new_fill_settings.png
  docs/training_manual/basic_map/img/new_symbol_layer.png
  docs/training_manual/basic_map/img/pattern_fill_distances.png
  docs/training_manual/basic_map/img/pattern_fill_size.png
  docs/training_manual/basic_map/img/places_layer_properties.png
  docs/training_manual/basic_map/img/scale_dependent_visibility.png
  docs/training_manual/basic_map/img/simple_fill_move_down.png
  docs/training_manual/basic_map/img/simple_fill_selected.png
  docs/training_manual/basic_map/img/simple_marker_line_properties.png
  docs/training_manual/basic_map/img/svg_symbol_settings.png
  docs/training_manual/basic_map/img/symbol_levels_dialog.png
  docs/training_manual/basic_map/img/symbol_levels_main_dialog.png
  docs/training_manual/basic_map/symbology.rst
Labels: Screenshots, Training Manual, backport release_3.10

#5699 Training manual dynamic layout lesson update
  docs/training_manual/map_composer/dynamic_layout.rst
Labels: Text, Training Manual, backport release_3.10

#5710 Update the TM feature topology lesson to QGIS 3
  docs/training_manual/create_vector_data/img/areas_joined.png
  docs/training_manual/create_vector_data/img/corner_selected_move.png
  docs/training_manual/create_vector_data/img/new_park_area.png
  docs/training_manual/create_vector_data/img/node_example_result.png
  docs/training_manual/create_vector_data/img/simplify_line_dialog.png
  docs/training_manual/create_vector_data/img/simplify_line_example.png
  docs/training_manual/create_vector_data/img/zoom_to.png
  docs/training_manual/create_vector_data/topo_editing.rst
Labels: Screenshots, Training Manual, backport release_3.10

#5716 Some updates after review of #5710
  docs/training_manual/create_vector_data/img/set_snapping_options.png
  docs/training_manual/create_vector_data/topo_editing.rst
Labels: Training Manual, backport release_3.10

#5702 A bit more details on "Duplicate layers" and "Copy layers" tools
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5714 Update the TM reprojecting and transforming data lesson
  docs/training_manual/vector_analysis/reproject_transform.rst
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5719 TM: Update the basic analysis lesson
  docs/training_manual/vector_analysis/basic_analysis.rst
  docs/training_manual/vector_analysis/img/buffer_saving.png
  docs/training_manual/vector_analysis/img/buildings_area_calculator.png
  docs/training_manual/vector_analysis/img/buildings_area_query.png
  docs/training_manual/vector_analysis/img/dissolve_buffer_results.png
  docs/training_manual/vector_analysis/img/dissolve_buffer_setup.png
  docs/training_manual/vector_analysis/img/location_select_dialog.png
  docs/training_manual/vector_analysis/img/osm_swellendam.png
  docs/training_manual/vector_analysis/img/osm_swellendam_2.png
  docs/training_manual/vector_analysis/img/roads_buffer_result.png
  docs/training_manual/vector_analysis/img/save_roads_34S.png
  docs/training_manual/vector_analysis/img/school_roads_intersect.png
  docs/training_manual/vector_analysis/img/vector_buffer_setup.png
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5720 Update the network analysis part of the vector analysis TM module
  docs/training_manual/vector_analysis/img/shortest_point.png
  docs/training_manual/vector_analysis/img/shortest_point_attributes.png
  docs/training_manual/vector_analysis/network_analysis.rst
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5721 Update the TM spatial statistics lesson
  docs/training_manual/vector_analysis/img/basic_statistics_results.png
  docs/training_manual/vector_analysis/img/histogram_export.png
  docs/training_manual/vector_analysis/img/histogram_export_zoom.png
  docs/training_manual/vector_analysis/img/nearest_neighbour_example.png
  docs/training_manual/vector_analysis/img/polygon_centroid_mean.png
  docs/training_manual/vector_analysis/img/random_points_result.png
  docs/training_manual/vector_analysis/img/random_points_setup.png
  docs/training_manual/vector_analysis/img/random_samples_result.png
  docs/training_manual/vector_analysis/img/result_viewer.png
  docs/training_manual/vector_analysis/img/roads_hull_setup.png
  docs/training_manual/vector_analysis/img/sample_raster_dialog.png
  docs/training_manual/vector_analysis/spatial_statistics.rst
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5730 Update travis to most recent Python and linux distribution
  .travis.yml
Labels: backport release_3.10

#5733 Update the TM raster module, first part (working with raster data)
  docs/training_manual/rasters/data_manipulation.rst
  docs/training_manual/rasters/img/build_virtual_raster.png
  docs/training_manual/rasters/img/merge_rasters.png
  docs/training_manual/rasters/img/raster_step_one.png
  docs/training_manual/rasters/img/warp_rasters.png
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5734 Update TM raster symbology
  docs/training_manual/rasters/changing_symbology.rst
  docs/training_manual/rasters/img/click_transparency.png
  docs/training_manual/rasters/img/dem_layer_properties.png
  docs/training_manual/rasters/img/dem_pseudocolor_properties.png
  docs/training_manual/rasters/img/good_raster.png
  docs/training_manual/rasters/img/pseudocolor_raster.png
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5737 Update TM terrain analysis
  docs/training_manual/rasters/img/identify_raster.png
  docs/training_manual/rasters/img/identify_raster_table.png
  docs/training_manual/rasters/img/raster_calculator.png
  docs/training_manual/rasters/img/reclassify_setup.png
  docs/training_manual/rasters/img/reclassify_table.png
  docs/training_manual/rasters/img/value_tool.png
  docs/training_manual/rasters/terrain_analysis.rst
Labels: Screenshots, Text, Training Manual, backport release_3.10

#5715 TM Module 3.1.1 Update
  docs/training_manual/basic_map/img/attribute_data_preview.png
  docs/training_manual/basic_map/img/flash_feature.png
  docs/training_manual/basic_map/img/select_polygon.png
  docs/training_manual/basic_map/img/select_record.png
  docs/training_manual/basic_map/img/select_record2.png
  docs/training_manual/basic_map/img/zoom_to_feature.png
  docs/training_manual/basic_map/vector_data.rst
Labels: Training Manual, backport release_3.10

#5748 Update TM to reference a GeoPackage data source instead of Shapefile Format data sources
  docs/training_manual/introduction/mapviewnavigation.rst
Labels: Training Manual, backport release_3.10

#5611 Update GUI labels for ArcGIS services
  docs/user_manual/introduction/qgis_gui.rst
  docs/user_manual/managing_data_source/opening_data.rst
  docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
Labels: 3.14

#5767 [TM] Update vector classification lesson (part 1)
  docs/training_manual/vector_classification/classification.rst
  docs/training_manual/vector_classification/img/area_gradient_select.png
  docs/training_manual/vector_classification/img/calculate_field_dialog.png
  docs/training_manual/vector_classification/img/categories_explained.png
  docs/training_manual/vector_classification/img/categorised_style_settings.png
  docs/training_manual/vector_classification/img/categorised_styles.png
  docs/training_manual/vector_classification/img/change_layer_color.png
  docs/training_manual/vector_classification/img/empty_category.png
  docs/training_manual/vector_classification/img/landuse_gradient_selected.png
  docs/training_manual/vector_classification/img/rule_based_classification.png
Labels: 3.10

#5766 TM: Update title expresssions - variables
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/print_composer/composer_items/composer_legend.rst
  docs/user_manual/working_with_vector/expression.rst
Labels: User Manual, backport release_3.10
