Repository qgis/QGIS-Documentation, pull requests merged in 2020-11, with the labels that each got.

#6152 GetProjectSettings legend group
  docs/server_manual/services.rst
Labels: backport release_3.16

#6161 add data defined option for 3D
  docs/user_manual/working_with_vector/img/3d_extrusion.png
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.16

#6233 rename vector field
  docs/user_manual/processing_algs/qgis/vectortable.rst
Labels: backport release_3.16

#6221 [3.16] Add close_path parameter to points to path alg
  docs/user_manual/processing_algs/qgis/vectorcreation.rst
Labels: Processing Alg

#6238 Remove references to travis for docs infrastructure
  .travis.yml
  README.md
  docs/documentation_guidelines/first_contribution.rst
  docs/pyqgis_developer_cookbook/processing.rst
Labels: backport release_3.16

#6220 Update Points to path algorithm
  docs/user_manual/processing_algs/qgis/vectorcreation.rst
  substitutions.txt
Labels: Processing Alg

#6193 Add some basic usage information about qgis_process
  docs/user_manual/processing/index.rst
  docs/user_manual/processing/standalone.rst
Labels: backport release_3.16

#6237 Add precision to translation rules
  docs/documentation_guidelines/do_translations.rst
Labels: backport release_3.16

#6232 Add the "Relations" group in Expressions dialog
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/working_with_vector/expression.rst
  docs/user_manual/working_with_vector/functions_list.rst
Labels: backport release_3.16

#6225 Update and split into tabs the 3d configuration dialog
  docs/user_manual/introduction/img/3dmapconfiguration.png
  docs/user_manual/introduction/img/3dmapconfiguration_lights.png
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.16

#6222 Use click-click for rotate and offset point symbols tools
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.16

#6218 Add gdal contour_polygon algorithm
  docs/user_manual/processing_algs/gdal/rasterextraction.rst
Labels: backport release_3.16

#6165 Add Vector Tile Service
  docs/user_manual/managing_data_source/img/vector_tiles_maptilerplanet.png
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.16

#6263 Added colon to let expression show as expression in build docs
  docs/training_manual/complete_analysis/analysis_exercise.rst
Labels: backport release_3.16

#6153 QgsVectorLayerUtils class
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.16

#6270 Doctest build is turning QgsMapLayer into QgsVectorLayer
  docs/pyqgis_developer_cookbook/legend.rst
Labels: backport release_3.16

#6040 [pyqgis] add a small QgsSpatialIndexKDBush description
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.16

#6274 [pyqgis] IndexKDBush index
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.16

#6276 Connect the array functions to the overlay-* functions
  docs/user_manual/working_with_vector/functions_list.rst
Labels: backport release_3.16

#6257 Add examples of expressions to display layer values
  docs/user_manual/print_composer/composer_items/composer_label.rst
Labels: backport release_3.16

#6280 Two more renaming fil;e (adding capital R)
  docs/training_manual/complete_analysis/analysis_exercise.rst
Labels: backport release_3.16

#6269 Update zonal statistics algorithm ID to use help button efficiently
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: backport release_3.16

#6267 Update url of gdal programs
  docs/pyqgis_developer_cookbook/vector.rst
  docs/user_manual/managing_data_source/supported_data.rst
  docs/user_manual/processing_algs/gdal/rasteranalysis.rst
  docs/user_manual/processing_algs/gdal/rasterconversion.rst
  docs/user_manual/processing_algs/gdal/rasterextraction.rst
  docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
  docs/user_manual/processing_algs/gdal/rasterprojections.rst
  docs/user_manual/processing_algs/gdal/vectorconversion.rst
  docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
  docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
Labels: backport release_3.16

#6268 [TM] Some cleanup to analysis exercise
  docs/training_manual/complete_analysis/analysis_exercise.rst
Labels: backport release_3.16

#6289 Small mod to start service or socket after enable
  docs/server_manual/getting_started.rst
Labels: backport release_3.16

#6254 3D symbols can be created in Style Manager
  docs/user_manual/style_library/3d_symbols.rst
  docs/user_manual/style_library/img/3d_extrusion.png
  docs/user_manual/style_library/img/3d_line_symbol.png
  docs/user_manual/style_library/img/3d_point_symbol.png
  docs/user_manual/style_library/img/3d_polygon_symbol.png
  docs/user_manual/style_library/img/stylemanager.png
  docs/user_manual/style_library/index.rst
  docs/user_manual/style_library/style_manager.rst
  docs/user_manual/working_with_vector/img/3d_extrusion.png
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.16

#6290 clipping settings for map items
  docs/user_manual/print_composer/composer_items/composer_map.rst
Labels: backport release_3.16

#6291 tracing on curved geometries
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.16

#6293 Various changes on label settings
  docs/user_manual/style_library/label_settings.rst
Labels: backport release_3.16

#6295 Update line labels placement
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/style_library/label_settings.rst
  static/common/mActionLabelAnchorCenter.png
  static/common/mActionLabelAnchorCustom.png
  static/common/mActionLabelAnchorEnd.png
  static/common/mActionLabelAnchorStart.png
  substitutions.txt
Labels: backport release_3.16
