Repository qgis/QGIS-Documentation, pull requests merged in 2020-08, with the labels that each got.

#5948 Update link to INSTALL
  docs/developers_guide/qtcreator.rst
  docs/user_manual/introduction/getting_started.rst
Labels: backport release_3.10

#5952 Fix pdf creation
  Makefile
Labels: backport release_3.10

#5898 enhance nearest neighbor analysis algorithm
  docs/user_manual/processing_algs/qgis/img/normal_distribution.png
  docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Labels: Processing Alg, backport release_3.10

#5958 Explain RULELABEL AUTO option in GetLegendGraphics
  docs/server_manual/services.rst
Labels: 3.14

#5896 Adds missing Processing Model inputs to the list
  docs/user_manual/processing/console.rst
  docs/user_manual/processing/modeler.rst
Labels: Graphical modeler, Processing

#5977 Change to numref for figure references in the user manual
  docs/user_manual/introduction/qgis_gui.rst
  docs/user_manual/print_composer/composer_items/composer_attribute_table.rst
  docs/user_manual/print_composer/composer_items/composer_map3d.rst
  docs/user_manual/print_composer/create_output.rst
  docs/user_manual/working_with_mesh/mesh_properties.rst
  docs/user_manual/working_with_ogc/ogc_client_support.rst
  docs/user_manual/working_with_vector/attribute_table.rst
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10

#5976 Remote UI files and broken link fixing
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10

#5981 Force spring clean job before running the all task
  Makefile
Labels: backport release_3.10

#5983 No icon to indicate the OS screenshots are taken from
  docs/user_manual/preamble/conventions.rst
Labels: backport release_3.10

#5997 Use string comparison operator
  scripts/find_set_subst.py
Labels: backport release_3.10

#5971 Fix and enhance auth config chapter
  docs/user_manual/auth_system/auth_overview.rst
  docs/user_manual/auth_system/img/auth-editor-configs_utilities-menu.png
Labels: backport release_3.10

#5980 [pyqgis] Add broken path handling with QgsPathResolver
  docs/pyqgis_developer_cookbook/loadproject.rst
Labels: PyQGIS Cookbook, backport release_3.10

#6004 [Processing] add missing parameters to random points in extent
  docs/user_manual/processing_algs/qgis/vectorcreation.rst
Labels: Processing Alg

#5973 [pyqgis] add a code snippet specific for plugins
  docs/pyqgis_developer_cookbook/plugins/snippets.rst
Labels: PyQGIS Cookbook, backport release_3.10

#5756 Add expression example
  docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.10

#6027 Processing modeler big enhancements
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/processing/img/help_edition.png
  docs/user_manual/processing/img/model_group_box.png
  docs/user_manual/processing/img/model_reorder_inputs.png
  docs/user_manual/processing/img/modeler_canvas.png
  docs/user_manual/processing/img/modeler_right_click.png
  docs/user_manual/processing/img/models_model.png
  docs/user_manual/processing/img/models_parameters.png
  docs/user_manual/processing/img/models_parameters3.png
  docs/user_manual/processing/img/models_parameters4.png
  docs/user_manual/processing/img/models_parameters5.png
  docs/user_manual/processing/modeler.rst
  static/common/mActionEditHelpContent.png
  static/common/mActionSaveAsPython.png
  static/common/mIconFieldInteger.png
  static/common/mIconModelOutput.png
  substitutions.txt
Labels: Graphical modeler, Processing

#6044 QGIS_SERVER_DISABLE_GETPRINT setting environment
  docs/server_manual/config.rst
Labels: Server

#6041 Open qgis with grass
  docs/training_manual/grass/grass_setup.rst
Labels: Training Manual, backport release_3.10

#6038 change XML to qmd extension metadata
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10

#6046 Autofix broken paths
  docs/user_manual/managing_data_source/opening_data.rst
Labels: User Manual, backport release_3.10
