Repository qgis/QGIS-Documentation, pull requests merged in 2020-01, with the labels that each got.

#4711 Add documentation for the GDAL raster calculator (GDAL misc)
  source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Labels: Processing Alg, backport release_3.4

#4715 Add the gdal retile algorithm
  source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Labels: Processing Alg, backport release_3.4

#4724 GDAL Retile alg, remove the mention of ESRI Shapefile format output
  source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Labels: backport release_3.4

#4749 Tables for alg params - lastools
  source/docs/user_manual/processing_algs/lidartools/lastools.rst
Labels: Processing Alg, backport release_3.4

#4753 project files - some minor fixes
  source/docs/user_manual/introduction/img/new_project.png
  source/docs/user_manual/introduction/project_files.rst
Labels: Screenshots, Text, User Manual, enhancement

#4743 Update the graphical modeller documentation to QGIS 3
  source/docs/user_manual/processing/img/deactivated.png
  source/docs/user_manual/processing/img/help_edition.png
  source/docs/user_manual/processing/img/modeler_canvas.png
  source/docs/user_manual/processing/img/modeler_right_click.png
  source/docs/user_manual/processing/img/models_model.png
  source/docs/user_manual/processing/img/models_parameters.png
  source/docs/user_manual/processing/img/models_parameters2.png
  source/docs/user_manual/processing/img/models_parameters3.png
  source/docs/user_manual/processing/img/models_parameters4.png
  source/docs/user_manual/processing/modeler.rst
Labels: Screenshots, backport release_3.4

#4767 Add information about LAStools to 3rdParty
  source/docs/user_manual/processing/3rdParty.rst
Labels: IN PROGRESS, Processing

#4773 Update screenshots - introduction
  source/docs/user_manual/introduction/img/annotation.png
  source/docs/user_manual/introduction/img/color_selector_recent_colors.png
  source/docs/user_manual/introduction/img/identify_features.png
  source/docs/user_manual/introduction/img/layer_styling.png
  source/docs/user_manual/introduction/img/style_combobox.png
Labels: Screenshots

#4774 TauDEM Basic grid analysis - Tables for parameters
  source/docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst
Labels: Low Priority, Processing Alg, backport release_3.4

#4772 Update sceenshots for raster properties to QGIS 3
  source/docs/user_manual/working_with_raster/img/rasterHistogram.png
  source/docs/user_manual/working_with_raster/img/rasterLegend.png
  source/docs/user_manual/working_with_raster/img/rasterMetadata.png
  source/docs/user_manual/working_with_raster/img/rasterMultibandColor.png
  source/docs/user_manual/working_with_raster/img/rasterPalettedUniqueValue.png
  source/docs/user_manual/working_with_raster/img/rasterPyramids.png
  source/docs/user_manual/working_with_raster/img/rasterRendering.png
  source/docs/user_manual/working_with_raster/img/rasterServer.png
  source/docs/user_manual/working_with_raster/img/rasterTransparency.png
  source/docs/user_manual/working_with_raster/raster_properties.rst
Labels: Screenshots, User Manual

#4795 Custom CRS now allows the use of WKT strings fixes #4655 fixes #4654
  source/docs/user_manual/working_with_projections/img/customProjectionDialog.png
  source/docs/user_manual/working_with_projections/working_with_projections.rst
Labels: 3.10

#4801 Misc review fixes
  source/docs/user_manual/processing/3rdParty.rst
  source/docs/user_manual/processing_algs/qgis/cartography.rst
  source/docs/user_manual/processing_algs/qgis/database.rst
  source/docs/user_manual/processing_algs/qgis/layertools.rst
  source/docs/user_manual/processing_algs/qgis/modelertools.rst
  source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
  source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
  source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
  source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
  source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
  source/docs/user_manual/processing_algs/qgis/vectortable.rst
  source/docs/user_manual/working_with_raster/raster_properties.rst
  source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: backport release_3.10

#4538 [server] Add NO_MTEXT and FORCE_2D dxf export parameters
  source/docs/user_manual/working_with_ogc/server/services.rst
Labels: 3.12

#4792 Removes duplicated Retangle, Oval, Diamonds Fixes #4791
  source/docs/user_manual/processing_algs/qgis/img/rectangles_ovals_diamond.png
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: 3.12

#4799 Default project file format Fix #4798
  source/docs/user_manual/introduction/qgis_configuration.rst
Labels: 3.12

#4810 Fix list of options rendering
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.10, backport release_3.4

#4800 Chapter 13 (Managing Data Sources) - screenshots - updates to 3.10
  source/docs/user_manual/managing_data_source/create_layers.rst
  source/docs/user_manual/managing_data_source/img/addrasterlayerdialog.png
  source/docs/user_manual/managing_data_source/img/addvectorlayerdialog.png
  source/docs/user_manual/managing_data_source/img/db_manager.png
  source/docs/user_manual/managing_data_source/img/geotiffopendialog.png
  source/docs/user_manual/managing_data_source/img/newpostgisconnection.png
  source/docs/user_manual/managing_data_source/img/shapefileloaded.png
  source/docs/user_manual/managing_data_source/img/shapefileopendialog.png
  source/docs/user_manual/managing_data_source/img/xyz_tiles_dialog_osm.png
  source/docs/user_manual/managing_data_source/opening_data.rst
  source/docs/user_manual/managing_data_source/supported_data.rst
Labels: Screenshots, User Manual, backport release_3.10

#4334 Add hash functions
  source/docs/user_manual/working_with_vector/expression.rst
Labels: 3.12

#4816 Fix some issues with the sorting of geometry functions (expressions)
  source/docs/user_manual/working_with_vector/expression.rst
Labels: Low Priority, User Manual, backport release_3.10, backport release_3.4, enhancement

#4796 Use "value" as standard name fix #4230
  source/docs/user_manual/working_with_vector/img/categorysymbol_ng_line.png
  source/docs/user_manual/working_with_vector/img/graduatedsymbol_ng_line.png
  source/docs/user_manual/working_with_vector/img/label_menu_text.png
  source/docs/user_manual/working_with_vector/vector_properties.rst
Labels: 3.10, backport release_3.10

#4815 Update chapter 10 (projections) to reflect GUI changes
  source/docs/user_manual/working_with_projections/img/nadgrids_example.png
  source/docs/user_manual/working_with_projections/working_with_projections.rst
Labels: Screenshots, Text, User Manual, backport release_3.10

#4823 More fixes to opening data section
  source/docs/user_manual/managing_data_source/create_layers.rst
  source/docs/user_manual/managing_data_source/img/de/addvectorlayerdialog.png
  source/docs/user_manual/managing_data_source/img/de/editNewSpatialite.png
  source/docs/user_manual/managing_data_source/img/de/editNewVector.png
  source/docs/user_manual/managing_data_source/img/de/shapefileloaded.png
  source/docs/user_manual/managing_data_source/img/de/shapefileopendialog.png
  source/docs/user_manual/managing_data_source/img/fr/addvectorlayerdialog.png
  source/docs/user_manual/managing_data_source/img/geotiffopendialog.png
  source/docs/user_manual/managing_data_source/img/shapefileopendialog.png
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4824 Update the description of the preview of XYZ Tiles in the browser after review
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10, enhancement

#4825 Avoid an "Uncaught TypeError: a.indexOf is not a function"
  themes/qgis-theme/static/qgis-site.js
Labels: ToDocOrNotToDoc?

#4833 Move the mesh data opening instructions
  source/docs/user_manual/managing_data_source/img/mesh_datasource_manager.png
  source/docs/user_manual/managing_data_source/opening_data.rst
  source/docs/user_manual/working_with_mesh/img/mesh_datasource_manager.png
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
Labels: backport release_3.10

#4834 Document contextual menu for changing symbol properties for paletted and singleband pseudocolor
  source/docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.10, backport release_3.4

#4839 Update the extent dropdown screenshot to reflect the QGIS 3 GUI
  source/docs/user_manual/processing/img/extent.png
Labels: Processing, Screenshots, User Manual, backport release_3.10, backport release_3.4

#4840 Update after review of #4834 (Document contextual menu for changing symbol properties for paletted and singleband pseudocolor)
  source/docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.10

#4850 Rename and remove favorites
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10, backport release_3.4

#4835 Document the "dynamic stretching" option for raster layers
  source/docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.10, backport release_3.4

#4847 Documenting "Saving paletted raster renderer color tables"
  source/docs/user_manual/working_with_raster/raster_properties.rst
Labels: Text, User Manual, backport release_3.10, backport release_3.4

#4851 Exploration of QGS project file contents in the browser
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4848 Remove google plus mention in the footer
  themes/qgis-theme/page.html
  themes/qgis-theme/static/images/footer-gplus.png
  themes/qgis-theme/static/qgis-style.css
  themes/qgis-theme/static/qgis-style.less
Labels: backport release_3.10, backport release_3.4

#4863 Fix column width in PDF - script parameters
  source/docs/user_manual/processing/scripts.rst
Labels: PDF Docs, backport release_3.10
