Repository qgis/QGIS-Documentation, pull requests merged in 2020-07, with the labels that each got.

#5785 Expression variables, sorting, text adjustments
  docs/user_manual/working_with_vector/expression.rst
Labels: User Manual, backport release_3.10

#5765 Document WFS3 sorting
  docs/user_manual/working_with_ogc/server/services.rst
Labels: 3.16

#5791 Add version information for WFS feature sorting
  docs/user_manual/working_with_ogc/server/services.rst
Labels: 3.16

#5774 Make tables with a lot of content render correctly in pdf file
  docs/documentation_guidelines/writing.rst
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/qgis_gui.rst
  docs/user_manual/processing/scripts.rst
  docs/user_manual/processing_algs/gdal/rasteranalysis.rst
  docs/user_manual/processing_algs/gdal/rasterconversion.rst
  docs/user_manual/processing_algs/gdal/rasterextraction.rst
  docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
  docs/user_manual/processing_algs/gdal/rasterprojections.rst
  docs/user_manual/processing_algs/gdal/vectorconversion.rst
  docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
  docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
  docs/user_manual/processing_algs/lidartools/lastools.rst
  docs/user_manual/processing_algs/qgis/cartography.rst
  docs/user_manual/processing_algs/qgis/database.rst
  docs/user_manual/processing_algs/qgis/filetools.rst
  docs/user_manual/processing_algs/qgis/interpolation.rst
  docs/user_manual/processing_algs/qgis/layertools.rst
  docs/user_manual/processing_algs/qgis/modelertools.rst
  docs/user_manual/processing_algs/qgis/networkanalysis.rst
  docs/user_manual/processing_algs/qgis/plots.rst
  docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
  docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
  docs/user_manual/processing_algs/qgis/rastertools.rst
  docs/user_manual/processing_algs/qgis/vectoranalysis.rst
  docs/user_manual/processing_algs/qgis/vectorcreation.rst
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
  docs/user_manual/processing_algs/qgis/vectoroverlay.rst
  docs/user_manual/processing_algs/qgis/vectorselection.rst
  docs/user_manual/processing_algs/qgis/vectortable.rst
  docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst
Labels: backport release_3.10

#5796 Update TauDEM basic grid analysis algorithms
  docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst
Labels: Processing Alg, User Manual, backport release_3.10

#5795 Update the TauDEM specialised grid analysis algs
  docs/user_manual/processing_algs/taudem/specialized_grid_analysis_tools.rst
Labels: Processing Alg, User Manual, backport release_3.10

#5804 Update specialized_grid_analysis_tools.rst
  docs/user_manual/processing_algs/taudem/specialized_grid_analysis_tools.rst
Labels: backport release_3.10

#5809 Update network_analysis.rst
  docs/training_manual/vector_analysis/network_analysis.rst
Labels: Training Manual, backport release_3.10

#5816 Fix some minor issues in processing history.rst
  docs/user_manual/processing/history.rst
Labels: Processing, User Manual, backport release_3.10

#5789 Update the QGIS features, part I
  docs/user_manual/preamble/features.rst
Labels: User Manual, backport release_3.10, enhancement

#5823 Add to the features list
  docs/user_manual/preamble/features.rst
Labels: User Manual, backport release_3.10, enhancement

#5825 More feature updates, including graphical modeller, authentication and locator
  docs/user_manual/preamble/features.rst
Labels: User Manual, backport release_3.10

#5440 Add a separate Browser panel section in the QGIS GUI chapter
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/index.rst
  docs/user_manual/introduction/browser.rst
  docs/user_manual/introduction/img/browser_p_properties_w.png
  docs/user_manual/introduction/img/browser_panel.png
  static/common/browser_collapse.png
  static/common/browser_expand.png
  substitutions.txt
Labels: User Manual, enhancement

#5831 Update QGIS features with information about spreadsheet support
  docs/user_manual/preamble/features.rst
Labels: User Manual, backport release_3.10, enhancement

#5834 Creating layers gdal
  docs/user_manual/managing_data_source/create_layers.rst
Labels: Processing, backport release_3.10

#5835 Fix documentation build
  docs/pyqgis_developer_cookbook/loadlayer.rst
  docs/pyqgis_developer_cookbook/plugins/snippets.rst
Labels: backport release_3.10

#5839 Document drag and drop of images to layouts (and some minor updates)
  docs/user_manual/print_composer/composer_items/composer_image.rst
Labels: 3.12

#5846 Fix typo native.buffer -> native:buffer
  docs/user_manual/processing/console.rst
Labels: backport release_3.10

#5841 Add documentation for 3D Map views in layouts
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/print_composer/composer_items/composer_map3d.rst
  docs/user_manual/print_composer/composer_items/img/3dmap_properties.png
  docs/user_manual/print_composer/composer_items/index.rst
  docs/user_manual/print_composer/img/print_composer_blank.png
  static/common/mActionAdd3DMap.png
  substitutions.txt
Labels: 3.4, Print layout / Atlas / Report

#5852 Update the print composer blank screenshot
  docs/user_manual/print_composer/img/print_composer_blank.png
Labels: Print layout / Atlas / Report, Screenshots

#5768 [TM] Update vector classification lesson (part 2)
  docs/training_manual/vector_classification/classification.rst
  docs/training_manual/vector_classification/img/add_area_column.png
  docs/training_manual/vector_classification/img/bad_landuse_labels.png
  docs/training_manual/vector_classification/img/categorisation_result.png
  docs/training_manual/vector_classification/img/criterion_else.png
  docs/training_manual/vector_classification/img/criterion_refined_list.png
  docs/training_manual/vector_classification/img/criterion_refined_midway.png
  docs/training_manual/vector_classification/img/field_calculator_top.png
  docs/training_manual/vector_classification/img/geometry_area_select.png
  docs/training_manual/vector_classification/img/query_builder_example.png
  docs/training_manual/vector_classification/img/rule_based_map_result.png
  docs/training_manual/vector_classification/img/rule_style_result.png
Labels: 3.10

#5856 Add a link to the documentation index in the documentation sidebar
  themes/rtd_qgis/layout.html
Labels: backport release_3.10, enhancement

#5862 No more "fix me" link
  docs/documentation_guidelines/first_contribution.rst
Labels: backport release_3.10

#5874 Some fixes to the ESRI Shapefile format description
  docs/user_manual/managing_data_source/supported_data.rst
Labels: backport release_3.10

#5868 add doc for createAlgorithmDialog and execAlgorithmDialog
  docs/user_manual/processing/console.rst
Labels: 3.0, Code, Processing, User Manual, backport release_3.10

#5783 add documentation for OTB provider
  docs/user_manual/processing/3rdParty.rst
  docs/user_manual/processing_algs/index.rst
  docs/user_manual/processing_algs/otb.rst
Labels: Processing, Processing Alg, User Manual, backport release_3.10

#5869 Add child features aggregation function in select by value tool
  docs/user_manual/working_with_vector/attribute_table.rst
  docs/user_manual/working_with_vector/img/relation_select_by_value.png
Labels: backport release_3.10

#5886 Update the preamble
  docs/user_manual/index.rst
  docs/user_manual/preamble/foreword.rst
  docs/user_manual/preamble/help_and_support.rst
  docs/user_manual/preamble/preamble.rst
  docs/user_manual/preamble/whats_new.rst
Labels: User Manual, backport release_3.10

#5890 Better PDF rendering of minutes and seconds in dms
  conf.py
Labels: PDF Docs

#5905 Copy paste style
  docs/user_manual/introduction/general_tools.rst
Labels: backport release_3.10

#5769 Remove unnecessary sphinx extensions
  conf.py
Labels: backport release_3.10

#5923 Remove obsolete note on projection mismatch
  docs/training_manual/complete_analysis/analysis_combination.rst
Labels: backport release_3.10

#5901 Auth config for OGR sources
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#5917 Fix 2422
  docs/user_manual/introduction/project_files.rst
  docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.10

#5919 Updates to the supplementary exercise in the TM (ch 8)
  conf.py
  docs/training_manual/complete_analysis/analysis_exercise.rst
  docs/training_manual/vector_classification/classification.rst
  docs/user_manual/introduction/browser.rst
  docs/user_manual/preamble/preamble.rst
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: Training Manual, backport release_3.10

#5932 Remove obsolete note on algorithm parameters name
  docs/user_manual/processing_algs/index.rst
Labels: backport release_3.10

#5942 Corrected typo and switched name to correct tab
  docs/training_manual/create_vector_data/forms.rst
Labels: backport release_3.10

#5943 Broken format due to superfluous colon and missing parenthesis
  docs/training_manual/map_composer/dynamic_layout.rst
Labels: backport release_3.10
