Repository qgis/QGIS-Documentation, pull requests merged in 2020-03, with the labels that each got.

#4960 Review and cleanup of Metasearch chapter
  source/docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
Labels: backport release_3.10

#4957 Add elevation to project expression
  source/docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.10

#4955 Move up the Browser panel toolbar description
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4822 Add details on variety of supported online protocols data opening
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4959 Modularize the "loading a layer from a file" section
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4878 Change the name of the QGIS "Define layer projection" algorithm
  source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: 3.12, Processing Alg, backport release_3.10

#4956 Adds some details and aerate the browser panel description
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4977 Fix typo in task code
  source/docs/pyqgis_developer_cookbook/tasks.rst
Labels: Processing, PyQGIS Cookbook, backport release_3.10, backport release_3.4

#4972 Remove macOS outdated warning
  source/docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10

#4970 Add substitutions missing in the "footer"
  source/docs/user_manual/plugins/core_plugins/plugins_db_manager.rst
  source/docs/user_manual/working_with_vector/attribute_table.rst
Labels: backport release_3.10

#4985 Introduce the User expressions group
  source/docs/user_manual/working_with_vector/expression.rst
  source/docs/user_manual/working_with_vector/img/function_list.png
Labels: 3.12

#4975 Use more accurate reference sections
  source/docs/user_manual/introduction/general_tools.rst
  source/docs/user_manual/introduction/qgis_gui.rst
  source/docs/user_manual/plugins/index.rst
Labels: backport release_3.10

#4720 Default resampling settings
  source/docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.10

#4993 Add bad layer indicator
  source/docs/documentation_guidelines/substitutions.rst
  source/docs/user_manual/introduction/general_tools.rst
  source/substitutions.txt
  static/common/mIndicatorBadLayer.png
Labels: backport release_3.10

#5005 Reword mesh properties tabs section title to make them unique
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
Labels: backport release_3.10

#5013 Add the QgsProcessingParameterScale procesing parameter type
  source/docs/user_manual/processing/scripts.rst
Labels: 3.8, Processing, backport release_3.10

#5026 Title label decoration
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/introduction/general_tools.rst
  static/common/add_grid.png
  static/common/title_label.png
  substitutions.txt
Labels: Guidelines, User Manual, backport release_3.10

#5036 Some fixes to html build warnings
  conf.py
  docs/pyqgis_developer_cookbook/server.rst
  docs/training_manual/qgis_server/install.rst
  docs/training_manual/qgis_server/wms.rst
  venv.mk
Labels: backport release_3.10, backport release_3.4

#5040 Fixed reference
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5044 Add processing parameter types
  docs/documentation_guidelines/writing.rst
Labels: Processing, Processing Alg, User Manual, backport release_3.10

#5025 Update the report section of the user manual to QGIS 3.10 (new dir structure)
  docs/user_manual/print_composer/create_reports.rst
  docs/user_manual/print_composer/img/add_section.png
  docs/user_manual/print_composer/img/controlledbyreport.png
  docs/user_manual/print_composer/img/edit_group_body.png
  docs/user_manual/print_composer/img/export_options_reports.png
  docs/user_manual/print_composer/img/field_group.png
  docs/user_manual/print_composer/img/footer.png
  docs/user_manual/print_composer/img/header.png
  docs/user_manual/print_composer/img/headerfooter.png
  docs/user_manual/print_composer/img/ports.png
  docs/user_manual/print_composer/img/project-1.png
  docs/user_manual/print_composer/img/report-2.png
  docs/user_manual/print_composer/img/report1.png
  docs/user_manual/print_composer/img/report3.png
  docs/user_manual/print_composer/img/report4.png
  docs/user_manual/print_composer/img/report5.png
  docs/user_manual/print_composer/img/report_all_img.png
  docs/user_manual/print_composer/img/report_dynamic_picture.png
  docs/user_manual/print_composer/img/report_header.png
  docs/user_manual/print_composer/img/subsection.png
Labels: Screenshots, User Manual, backport release_3.10

#5022 Update the remove null geometries algorithm (include the remove empty option)
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: 3.14

#5035 Enable top banner for outdated/testing documentation
  conf.py
Labels: backport release_3.10, backport release_3.4

#5034 Indicate that doc build is possible on macOS
  README.rst
Labels: backport release_3.10, backport release_3.4

#5065 Cookbook revision: authmanager
  conf.py
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: Code, backport release_3.10, backport release_3.4

#5066 Update the QGIS R integration documentation
  conf.py
  docs/training_manual/processing/index.rst
  docs/training_manual/processing/r_syntax-table.rst
  docs/training_manual/processing/r_syntax.rst
  docs/user_manual/appendices/GNU_FDL.rst
  docs/user_manual/appendices/GNU_GPL.rst
  docs/user_manual/appendices/index.rst
  docs/user_manual/appendices/qgis_file_formats.rst
  docs/user_manual/appendices/qgis_r_syntax.rst
  docs/user_manual/index.rst
  docs/user_manual/processing/3rdParty.rst
Labels: Processing, Training Manual, User Manual, backport release_3.10, backport release_3.4

#5067 Cookbook revision canvas
  conf.py
  docs/pyqgis_developer_cookbook/canvas.rst
  testdata/airports.cpg
  testdata/airports.dbf
  testdata/airports.prj
  testdata/airports.shp
  testdata/airports.shx
Labels: Code, backport release_3.10, backport release_3.4

#5071 Fix indentation of GUI auth widgets list
  docs/pyqgis_developer_cookbook/authentication.rst
Labels: backport release_3.10

#5075 Update vectorgeneral.rst
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: 3.12

#5052 Add image decoration
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/img/image_decoration.png
  scripts/find_set_subst.py
Labels: High Priority, Screenshots, User Manual, backport release_3.10

#5070 Fix redirection link to the latest docs
  conf.py
  themes/rtd_qgis/layout.html
Labels: backport release_3.10, backport release_3.4

#5077 Double wording "the the"
  docs/user_manual/processing_algs/gdal/rasterprojections.rst
Labels: backport release_3.10

#5076 Typo corrected
  docs/user_manual/processing_algs/qgis/interpolation.rst
Labels: backport release_3.10

#5084 Add image decoration backported to 3.10
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/img/image_decoration.png
  scripts/find_set_subst.py
Labels: User Manual

#5091 Cookbook revision: cheat sheet
  conf.py
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
  testdata/file.qss
  testdata/sublayers.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5092 Cookbook revision: communicating
  conf.py
  docs/pyqgis_developer_cookbook/communicating.rst
Labels: Code, backport release_3.10, backport release_3.4

#5101 Cookbook revision: CRS (minor changes: it was already ok)
  docs/pyqgis_developer_cookbook/crs.rst
  testdata/sublayers.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5104 Cookbook revision: geometry
  docs/pyqgis_developer_cookbook/geometry.rst
Labels: Code, backport release_3.10, backport release_3.4

#5099 Typo corrected
  docs/user_manual/processing_algs/gdal/rasterextraction.rst
Labels: backport release_3.10, backport release_3.4

#5100 Cookbook revision: composer
  docs/pyqgis_developer_cookbook/composer.rst
Labels: Code, backport release_3.10, backport release_3.4

#5105 Cookbook revision: small tweaks
  docs/pyqgis_developer_cookbook/communicating.rst
  docs/pyqgis_developer_cookbook/composer.rst
  docs/pyqgis_developer_cookbook/expressions.rst
  docs/pyqgis_developer_cookbook/geometry.rst
  docs/pyqgis_developer_cookbook/intro.rst
Labels: Code, backport release_3.10, backport release_3.4

#5109 Cookbook revision: legend
  conf.py
  docs/pyqgis_developer_cookbook/legend.rst
Labels: Code, backport release_3.10, backport release_3.4

#5112 Cookbook revision: loadlayer
  docs/pyqgis_developer_cookbook/loadlayer.rst
  testdata/delimited_xy.csv
  testdata/layers.gpx
  testdata/sample.dxf
  testdata/sublayers.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5114 Typo corrected
  docs/user_manual/print_composer/overview_composer.rst
Labels: backport release_3.10

#5118 Update codingstandards.rst
  docs/developers_guide/codingstandards.rst
Labels: Code, backport release_3.10, backport release_3.4

#5117 Display the previous/next buttons to browse the docs
  conf.py
Labels: backport release_3.10, backport release_3.4

#5121 Cookbook revision: loadproject and network analysis
  docs/pyqgis_developer_cookbook/loadproject.rst
  docs/pyqgis_developer_cookbook/network_analysis.rst
  testdata/network.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5123 Cookbook revision: processing
  conf.py
  docs/pyqgis_developer_cookbook/processing.rst
  testdata/processing/__init__.py
  testdata/processing/processing_provider/__init__.py
  testdata/processing/processing_provider/example_processing_algorithm.py
  testdata/processing/processing_provider/provider.py
Labels: Code, backport release_3.10, backport release_3.4

#5130 Cookbook revision: rasters
  docs/pyqgis_developer_cookbook/raster.rst
  testdata/sublayers.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5093 Show only the relevant options in the bottom bar
  themes/rtd_qgis/versions.html
Labels: backport release_3.10, backport release_3.4

#5122 Remove non-existent/unused icon
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/introduction/qgis_gui.rst
  static/common/mActionCircleExtent.png
  substitutions.txt
Labels: backport release_3.10

#5132 Cookbook revision: vector layers
  conf.py
  docs/pyqgis_developer_cookbook/communicating.rst
  docs/pyqgis_developer_cookbook/vector.rst
  qgis-projects/python_cookbook/01_project.qgs
  testdata/network.gpkg
Labels: Code, backport release_3.10, backport release_3.4

#5138 Cookbook revision tasks
  conf.py
  docs/pyqgis_developer_cookbook/tasks.rst
Labels: Code, backport release_3.10, backport release_3.4

#5141 Updated reference and local substitutions
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5142 Updated reference and local substitutions
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5144 Typo corrected
  docs/user_manual/processing_algs/qgis/vectortable.rst
Labels: backport release_3.10, backport release_3.4

#5143 Typo corrected
  docs/pyqgis_developer_cookbook/legend.rst
Labels: backport release_3.10, backport release_3.4

#5150 Revert removal of vector core Plugins from QGIS GUI list
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5149 Indicate submenus in the General Tools chapter with the arrow
  docs/user_manual/introduction/general_tools.rst
Labels: backport release_3.10

#5139 Cookbook revision: settings
  docs/pyqgis_developer_cookbook/settings.rst
  docs/user_manual/introduction/qgis_configuration.rst
Labels: Code, backport release_3.10, backport release_3.4

#3840 Do not discourage people from using SSL to access postgres
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.4

#5165 Cookbook revision server
  conf.py
  docs/documentation_guidelines/cookbook_guidelines.rst
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/pyqgis_developer_cookbook/canvas.rst
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
  docs/pyqgis_developer_cookbook/communicating.rst
  docs/pyqgis_developer_cookbook/composer.rst
  docs/pyqgis_developer_cookbook/crs.rst
  docs/pyqgis_developer_cookbook/expressions.rst
  docs/pyqgis_developer_cookbook/geometry.rst
  docs/pyqgis_developer_cookbook/intro.rst
  docs/pyqgis_developer_cookbook/legend.rst
  docs/pyqgis_developer_cookbook/loadlayer.rst
  docs/pyqgis_developer_cookbook/loadproject.rst
  docs/pyqgis_developer_cookbook/network_analysis.rst
  docs/pyqgis_developer_cookbook/raster.rst
  docs/pyqgis_developer_cookbook/server.rst
  docs/pyqgis_developer_cookbook/settings.rst
  docs/pyqgis_developer_cookbook/tasks.rst
  docs/pyqgis_developer_cookbook/vector.rst
  qgis-projects/python_cookbook/01_project.qgs
  readme.rst
  testdata/airports.dbf
  testdata/airports.shp
  testdata/airports.shx
  testdata/network.gpkg
  testdata/sublayers.gpkg
Labels: Code

#5172 Updated arrows in menu items to --> and removed superfluous space
  docs/user_manual/processing/3rdParty.rst
Labels: backport release_3.10

#5171 Small changes
  docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.10

#5176 Added two periods after end of sentence
  docs/user_manual/processing_algs/qgis/cartography.rst
Labels: backport release_3.10

#5175 Cookbook revision: plugin layers + final cleanup
  .gitignore
  conf.py
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/pyqgis_developer_cookbook/canvas.rst
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
  docs/pyqgis_developer_cookbook/communicating.rst
  docs/pyqgis_developer_cookbook/composer.rst
  docs/pyqgis_developer_cookbook/crs.rst
  docs/pyqgis_developer_cookbook/expressions.rst
  docs/pyqgis_developer_cookbook/geometry.rst
  docs/pyqgis_developer_cookbook/legend.rst
  docs/pyqgis_developer_cookbook/loadlayer.rst
  docs/pyqgis_developer_cookbook/loadproject.rst
  docs/pyqgis_developer_cookbook/network_analysis.rst
  docs/pyqgis_developer_cookbook/plugins/pluginlayer.rst
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
  docs/pyqgis_developer_cookbook/plugins/releasing.rst
  docs/pyqgis_developer_cookbook/plugins/snippets.rst
  docs/pyqgis_developer_cookbook/processing.rst
  docs/pyqgis_developer_cookbook/raster.rst
  docs/pyqgis_developer_cookbook/server.rst
  docs/pyqgis_developer_cookbook/settings.rst
  docs/pyqgis_developer_cookbook/tasks.rst
  docs/pyqgis_developer_cookbook/vector.rst
  qgis-projects/python_cookbook/01_project.qgs
  qgis-projects/python_cookbook/airports.cpg
  qgis-projects/python_cookbook/airports.dbf
  qgis-projects/python_cookbook/airports.prj
  qgis-projects/python_cookbook/airports.shp
  qgis-projects/python_cookbook/airports.shx
  qgis-projects/python_cookbook/delimited_xy.csv
  qgis-projects/python_cookbook/file.qss
  qgis-projects/python_cookbook/layers.gpx
  qgis-projects/python_cookbook/network.gpkg
  qgis-projects/python_cookbook/processing/__init__.py
  qgis-projects/python_cookbook/processing/processing_provider/__init__.py
  qgis-projects/python_cookbook/processing/processing_provider/example_processing_algorithm.py
  qgis-projects/python_cookbook/processing/processing_provider/provider.py
  qgis-projects/python_cookbook/sample.dxf
  qgis-projects/python_cookbook/sublayers.gpkg
Labels: Code

#5157 Remove the 'Last updated' sentence in the left column
  themes/rtd_qgis/layout.html
Labels: backport release_3.10, backport release_3.4

#5181 Two typo's corrected
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.10, backport release_3.4

#5196 Not correct label ? Seems wrong !
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: backport release_3.10, backport release_3.4
