Repository qgis/QGIS-Documentation, pull requests merged in 2020-10, with the labels that each got.

#6157 Update cheat_sheet.rst
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
Labels: backport release_3.10

#6023 [pyqgis] add methods to QgsVectorLayer
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.10

#6156 Modify the confusing word
  docs/documentation_guidelines/first_contribution.rst
Labels: backport release_3.10

#6115 Update composer_map.rst
  docs/user_manual/print_composer/composer_items/composer_map.rst
Labels: backport release_3.10

#5902 Partial integration to the Browser Panel
  docs/user_manual/introduction/browser.rst
Labels: backport release_3.10

#6166 Add links to regular shapes digitizing section
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#6160 add query history DB Manager
  docs/user_manual/plugins/core_plugins/plugins_db_manager.rst
Labels: backport release_3.10

#6173 [Processing] describe the use of expression/variable in Execute SQL algorithm
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: Processing Alg, backport release_3.10

#6216 Fix NULL comparison
  docs/training_manual/vector_analysis/basic_analysis.rst
Labels: backport release_3.16

#6201 Check doctest build with GitHub action
  .github/workflows/doctest.yml
Labels: backport release_3.16

#6228 Add comments for code sample
  README.md
Labels: backport release_3.16

#6234 Update opening_data.rst (numref)
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.16
