Repository qgis/QGIS-Documentation, pull requests merged in 2020-02, with the labels that each got.

#4865 Fix some formatting issues and make code snippets more legible
  source/docs/pyqgis_developer_cookbook/canvas.rst
  source/docs/pyqgis_developer_cookbook/settings.rst
Labels: backport release_3.10, backport release_3.4

#4868 cdash updates (unit testing, developers guide)
  source/docs/developers_guide/unittesting.rst
Labels: Developer Manual

#4760 QGIS GUI part of the introduction - table updates, submenus added, illustration updates
  source/docs/documentation_guidelines/substitutions.rst
  source/docs/user_manual/introduction/img/panels.png
  source/docs/user_manual/introduction/img/startup.png
  source/docs/user_manual/introduction/img/toolbars.png
  source/docs/user_manual/introduction/qgis_gui.rst
  source/substitutions.txt
  static/common/mActionCircle2Points.png
  static/common/mActionCircle2TangentsPoint.png
  static/common/mActionCircle3Points.png
  static/common/mActionCircle3Tangents.png
  static/common/mActionCircleCenterPoint.png
  static/common/mActionCircleExtent.png
  static/common/mActionEllipseCenter2Points.png
  static/common/mActionEllipseCenterPoint.png
  static/common/mActionEllipseExtent.png
  static/common/mActionEllipseFoci.png
  static/common/mActionRectangle3PointsDistance.png
  static/common/mActionRectangle3PointsProjected.png
  static/common/mActionRectangleCenter.png
  static/common/mActionRectangleExtent.png
  static/common/mActionRegularPolygon2Points.png
  static/common/mActionRegularPolygonCenterCorner.png
  static/common/mActionRegularPolygonCenterPoint.png
Labels: Screenshots, backport release_3.10, enhancement

#4871 Adds usage of bookmarks from the browser panel
  source/docs/user_manual/introduction/general_tools.rst
  source/docs/user_manual/introduction/project_files.rst
  source/docs/user_manual/managing_data_source/opening_data.rst
  source/docs/user_manual/working_with_mesh/mesh_properties.rst
  source/substitutions.txt
  static/common/mActionNewBookmark.png
  static/common/mActionSharingExport.png
  static/common/mActionSharingImport.png
  static/common/mActionZoomToBookmark.png
Labels: backport release_3.10

#4899 Fix incomplete sentence
  source/docs/pyqgis_developer_cookbook/settings.rst
Labels: backport release_3.10, backport release_3.4

#4914 Missing letter in "fouth" = "fourth"
  source/docs/user_manual/processing_algs/lidartools/lastools.rst
Labels: backport release_3.10, backport release_3.4

#4913 Typo in name functie stddev
  source/docs/user_manual/processing_algs/lidartools/lastools.rst
Labels: backport release_3.10, backport release_3.4

#4915 Missing quote
  source/docs/user_manual/processing_algs/lidartools/lastools.rst
Labels: backport release_3.10, backport release_3.4

#4922 Remove the note to make the parameters table more compact
  source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.10

#4924 Some tweaks to improve code legibility
  source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
Labels: backport release_3.10

#4598 spawn-fcgi should be the prefered way compare to fcgiwrap
  source/docs/user_manual/working_with_ogc/server/getting_started.rst
Labels: backport release_3.10

#4930 Update the R section of third party tools for QGIS 3, the Processing R Provider plugin and resource sharing
  source/docs/user_manual/processing/3rdParty.rst
  source/docs/user_manual/processing/img/processing_toolbox_r_install.png
  source/docs/user_manual/processing/img/processing_toolbox_r_scripts.png
  source/docs/user_manual/processing/img/rscript_folder.png
  source/docs/user_manual/processing/img/rscript_folder_add.png
Labels: backport release_3.10, backport release_3.4
