Repository qgis/QGIS-Documentation, pull requests merged in 2020-04, with the labels that each got.

#5199 update plugin metadata item
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
Labels: backport release_3.10, backport release_3.4

#5158 Harmonize instructions to build docs within OS
  README.rst
Labels: backport release_3.10, backport release_3.4

#5207 Use :guilabel: and not **[]**
  docs/user_manual/working_with_projections/working_with_projections.rst
Labels: backport release_3.10

#5208 Add icons available in the 3D map view panel
  docs/documentation_guidelines/substitutions.rst
  static/common/mAction3DNavigation.png
  static/common/mActionPlay.png
  static/common/mActionTiltDown.png
  static/common/mActionTiltUp.png
  substitutions.txt
Labels: backport release_3.10

#5216 Typo's
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.10, backport release_3.4

#5097 Remove the unnecessary confdir option from Makefile
  Makefile
Labels: backport release_3.10, backport release_3.4

#5096 Fix links for pages in the bottom bar
  conf.py
  docs_conf.yml
  themes/rtd_qgis/theme.conf
  themes/rtd_qgis/versions.html
Labels: backport release_3.10, backport release_3.4

#5221 Update and detail interaction with 3D map view
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.10

#5233 Cookbook revision: backport from master
  conf.py
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/pyqgis_developer_cookbook/canvas.rst
  docs/pyqgis_developer_cookbook/cheat_sheet.rst
  docs/pyqgis_developer_cookbook/communicating.rst
  docs/pyqgis_developer_cookbook/composer.rst
  docs/pyqgis_developer_cookbook/crs.rst
  docs/pyqgis_developer_cookbook/expressions.rst
  docs/pyqgis_developer_cookbook/geometry.rst
  docs/pyqgis_developer_cookbook/intro.rst
  docs/pyqgis_developer_cookbook/legend.rst
  docs/pyqgis_developer_cookbook/loadlayer.rst
  docs/pyqgis_developer_cookbook/loadproject.rst
  docs/pyqgis_developer_cookbook/network_analysis.rst
  docs/pyqgis_developer_cookbook/plugins/pluginlayer.rst
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
  docs/pyqgis_developer_cookbook/plugins/releasing.rst
  docs/pyqgis_developer_cookbook/plugins/snippets.rst
  docs/pyqgis_developer_cookbook/processing.rst
  docs/pyqgis_developer_cookbook/raster.rst
  docs/pyqgis_developer_cookbook/server.rst
  docs/pyqgis_developer_cookbook/settings.rst
  docs/pyqgis_developer_cookbook/tasks.rst
  docs/pyqgis_developer_cookbook/vector.rst
  docs/user_manual/introduction/qgis_configuration.rst
  doctest.dockerfile
  qgis-projects/python_cookbook/01_project.qgs
  qgis-projects/python_cookbook/airports.cpg
  qgis-projects/python_cookbook/airports.dbf
  qgis-projects/python_cookbook/airports.prj
  qgis-projects/python_cookbook/airports.shp
  qgis-projects/python_cookbook/airports.shx
  qgis-projects/python_cookbook/delimited_xy.csv
  qgis-projects/python_cookbook/file.qss
  qgis-projects/python_cookbook/layers.gpx
  qgis-projects/python_cookbook/network.gpkg
  qgis-projects/python_cookbook/processing/__init__.py
  qgis-projects/python_cookbook/processing/processing_provider/__init__.py
  qgis-projects/python_cookbook/processing/processing_provider/example_processing_algorithm.py
  qgis-projects/python_cookbook/processing/processing_provider/provider.py
  qgis-projects/python_cookbook/sample.dxf
  qgis-projects/python_cookbook/sublayers.gpkg
Labels: Code

#5234 Typo corrected
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10, backport release_3.4

#5214 Add 3D Map View toolbars and animation
  docs/user_manual/introduction/img/3dmapview.png
  docs/user_manual/introduction/qgis_gui.rst
  static/common/symbologyEdit.png
Labels: backport release_3.10

#5235 Remove blank line added below tables to increase bottom margin
  docs/developers_guide/unittesting.rst
  docs/documentation_guidelines/writing.rst
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
  docs/pyqgis_developer_cookbook/vector.rst
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/qgis_gui.rst
  docs/user_manual/processing/scripts.rst
  docs/user_manual/processing_algs/qgis/vectoranalysis.rst
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
  docs/user_manual/working_with_mesh/mesh_properties.rst
  docs/user_manual/working_with_ogc/server/services.rst
  docs/user_manual/working_with_vector/expression.rst
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10

#5250 corrected typo in line 31 of install.rst
  docs/training_manual/qgis_server/install.rst
Labels: backport release_3.10

#5249 Typo's corrected
  docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.10

#5244 Remove leftover folders from the training manual
  docs/training_manual/linfiniti-sphinx-theme/README.txt
  docs/training_manual/linfiniti-sphinx-theme/layout.html
  docs/training_manual/linfiniti-sphinx-theme/screenshot.jpeg
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/LICENSE.txt
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/css/bootstrap-responsive.css
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/css/bootstrap-responsive.min.css
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/css/bootstrap.css
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/css/bootstrap.min.css
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/img/glyphicons-halflings-white.png
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/img/glyphicons-halflings.png
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/js/bootstrap.js
  docs/training_manual/linfiniti-sphinx-theme/static/bootstrap/js/bootstrap.min.js
  docs/training_manual/linfiniti-sphinx-theme/static/img/note.png
  docs/training_manual/linfiniti-sphinx-theme/static/img/readme.txt
  docs/training_manual/linfiniti-sphinx-theme/static/img/warning.png
  docs/training_manual/linfiniti-sphinx-theme/static/linfiniti.css
  docs/training_manual/linfiniti-sphinx-theme/theme.conf
  docs/training_manual/planning_docs/course-plan-formal.odt
  docs/training_manual/planning_docs/deliverable_dates.odt
Labels: backport release_3.10

#5245 Use common substitutions when referring to icons
  docs/training_manual/vector_classification/classification.rst
  docs/training_manual/vector_classification/img/add_column_button.png
  docs/training_manual/vector_classification/label_tool.rst
Labels: backport release_3.10

#5255 Fix Appendices chapter table of content
  docs/pyqgis_developer_cookbook/authentication.rst
  docs/pyqgis_developer_cookbook/canvas.rst
  docs/pyqgis_developer_cookbook/network_analysis.rst
  docs/pyqgis_developer_cookbook/raster.rst
  docs/pyqgis_developer_cookbook/settings.rst
  docs/user_manual/appendices/GNU_FDL.rst
  docs/user_manual/appendices/GNU_GPL.rst
  docs/user_manual/appendices/index.rst
  docs/user_manual/appendices/qgis_file_formats.rst
  docs/user_manual/appendices/qgis_r_syntax.rst
  docs/user_manual/print_composer/create_reports.rst
Labels: backport release_3.10

#5256 Make the icons use a transparent background
  static/common/mActionAddAllToOverview.png
  static/common/mActionAddDb2Layer.png
  static/common/mActionAddDelimitedTextLayer.png
  static/common/mActionAddMssqlLayer.png
  static/common/mActionAddOgrLayer.png
  static/common/mActionAddOracleLayer.png
  static/common/mActionAddPostgisLayer.png
  static/common/mActionAddRasterLayer.png
  static/common/mActionAddSpatiaLiteLayer.png
  static/common/mActionAllEdits.png
  static/common/mActionAtlasSettings.png
  static/common/mActionCustomProjection.png
  static/common/mActionDuplicateLayer.png
  static/common/mActionFileNew.png
  static/common/mActionFileOpen.png
  static/common/mActionFileSave.png
  static/common/mActionFileSaveAs.png
  static/common/mActionOptions.png
  static/common/mActionPan.png
  static/common/mActionPanToSelected.png
  static/common/mActionPinLabels.png
  static/common/mActionRemoveAllFromOverview.png
  static/common/mActionRemoveLayer.png
  static/common/mActionRotateLabel.png
  static/common/mActionSetProjection.png
  static/common/mActionShowHideLabels.png
  static/common/mActionShowPluginManager.png
  static/common/mActionToggleEditing.png
  static/common/mActionZoomActual.png
  static/common/mActionZoomFullExtent.png
  static/common/mActionZoomIn.png
  static/common/mActionZoomLast.png
  static/common/mActionZoomNext.png
  static/common/mActionZoomOut.png
  static/common/mActionZoomToLayer.png
  static/common/mIconAtlas.png
  static/common/mIconDataDefine.png
  static/common/mIconExpression.png
  static/common/mIconExpressionFilter.png
  static/common/mIconProperties.png
  static/common/mIconPythonFile.png
  static/common/plugin-incompatible.png
  static/common/plugin-installed.png
  static/common/plugin-new.png
  static/common/plugin-upgrade.png
  static/common/plugin.png
  static/common/settings.png
  static/common/title_label.png
Labels: backport release_3.10

#5260 Document the Random Points on Lines algorithm
  docs/user_manual/processing_algs/qgis/img/randompointsalonglines_illustration.png
  docs/user_manual/processing_algs/qgis/img/randompointsonlines_nonzerodistance.png
  docs/user_manual/processing_algs/qgis/img/randompointsonlines_zerodistance.png
  docs/user_manual/processing_algs/qgis/vectorcreation.rst
Labels: 3.14, Processing Alg

#5269 Typo's corrected
  docs/user_manual/managing_data_source/create_layers.rst
Labels: backport release_3.10, backport release_3.4

#5276 Add layout lock icons substitutions
  docs/documentation_guidelines/substitutions.rst
  static/common/mActionLockItems.png
  static/common/mActionUnlockAll.png
  substitutions.txt
Labels: backport release_3.10

#5273 Errors fixed and an updated some information
  docs/training_manual/map_composer/map_composer.rst
  docs/training_manual/vector_classification/classification.rst
Labels: backport release_3.10

#5288 Small server code tweaks
  docs/pyqgis_developer_cookbook/server.rst
Labels: Code

#5262 Move the training manual icons to the static/common folder
  docs/training_manual/answers/answers.rst
  docs/training_manual/appendix/contribute.rst
  docs/training_manual/assessment/index.rst
  docs/training_manual/basic_map/symbology.rst
  docs/training_manual/basic_map/vector_data.rst
  docs/training_manual/complete_analysis/analysis_combination.rst
  docs/training_manual/complete_analysis/raster_to_vector.rst
  docs/training_manual/create_vector_data/actions.rst
  docs/training_manual/create_vector_data/create_new_vector.rst
  docs/training_manual/create_vector_data/forms.rst
  docs/training_manual/create_vector_data/topo_editing.rst
  docs/training_manual/database_concepts/adding_data.rst
  docs/training_manual/database_concepts/data_model.rst
  docs/training_manual/database_concepts/db_intro.rst
  docs/training_manual/database_concepts/queries.rst
  docs/training_manual/databases/db_browser.rst
  docs/training_manual/databases/db_manager.rst
  docs/training_manual/databases/spatialite.rst
  docs/training_manual/forestry/basic_lidar.rst
  docs/training_manual/forestry/forest_maps.rst
  docs/training_manual/forestry/map_georeferencing.rst
  docs/training_manual/forestry/parameters_calculation.rst
  docs/training_manual/forestry/results_map.rst
  docs/training_manual/forestry/stands_digitazing.rst
  docs/training_manual/forestry/systematic_sampling.rst
  docs/training_manual/forestry/updating_stands.rst
  docs/training_manual/foreword/intro.rst
  docs/training_manual/foreword/preparing_data.rst
  docs/training_manual/grass/grass_setup.rst
  docs/training_manual/grass/grass_tools.rst
  docs/training_manual/introduction/overview.rst
  docs/training_manual/introduction/preparation.rst
  docs/training_manual/map_composer/day_1_assignment.rst
  docs/training_manual/map_composer/dynamic_layout.rst
  docs/training_manual/map_composer/map_composer.rst
  docs/training_manual/online_resources/wfs.rst
  docs/training_manual/online_resources/wms.rst
  docs/training_manual/processing/log.rst
  docs/training_manual/qgis_plugins/fetching_plugins.rst
  docs/training_manual/qgis_plugins/plugin_examples.rst
  docs/training_manual/qgis_server/install.rst
  docs/training_manual/qgis_server/wms.rst
  docs/training_manual/rasters/changing_symbology.rst
  docs/training_manual/rasters/data_manipulation.rst
  docs/training_manual/rasters/terrain_analysis.rst
  docs/training_manual/spatial_databases/geometry.rst
  docs/training_manual/spatial_databases/simple_feature_model.rst
  docs/training_manual/spatial_databases/spatial_queries.rst
  docs/training_manual/vector_analysis/basic_analysis.rst
  docs/training_manual/vector_analysis/network_analysis.rst
  docs/training_manual/vector_analysis/reproject_transform.rst
  docs/training_manual/vector_analysis/spatial_statistics.rst
  docs/training_manual/vector_classification/attribute_data.rst
  docs/training_manual/vector_classification/classification.rst
  docs/training_manual/vector_classification/label_tool.rst
  static/common/basic.png
  static/common/comment.png
  static/common/hard.png
  static/common/moderate.png
  substitutions.txt
Labels: backport release_3.10

#5287 Document QGIS_SERVER_IGNORE_BAD_LAYERS
  docs/user_manual/working_with_ogc/server/config.rst
Labels: 3.14

#5298 Small text and renderer fixes
  docs/user_manual/processing/scripts.rst
Labels: backport release_3.10

#5296 Remove some references to qt4
  docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
  docs/training_manual/create_vector_data/actions.rst
  docs/training_manual/create_vector_data/forms.rst
  docs/training_manual/create_vector_data/img/qt_line_edit.png
  docs/training_manual/create_vector_data/img/qt_new_dialog.png
  docs/user_manual/auth_system/auth_workflows.rst
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/print_composer/overview_composer.rst
Labels: backport release_3.10

#5307 Better table display for getmap extra parameters
  docs/user_manual/working_with_ogc/server/services.rst
Labels: backport release_3.10

#5309 Document QGIS Development Server standalone application
  docs/user_manual/working_with_ogc/server/development_server.rst
  docs/user_manual/working_with_ogc/server/index.rst
Labels: Server, User Manual

#5312 Some cleanup after the server update
  docs/user_manual/working_with_ogc/server/getting_started.rst
  docs/user_manual/working_with_ogc/server/plugins.rst
Labels: backport release_3.10

#5299 Describe options depend on geometry
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: User Manual, backport release_3.10

#5332 Specify that trigonometric functions expect radians
  docs/user_manual/working_with_vector/expression.rst
Labels: backport release_3.10

#5335 Measurement ellipsoid is set in the "General" tab
  docs/user_manual/introduction/general_tools.rst
Labels: User Manual, backport release_3.10, backport release_3.4

#5345 Remove stray unicode character U+200B from plugins_gps
  docs/user_manual/working_with_gps/plugins_gps.rst
Labels: backport release_3.10, backport release_3.4

#5348 Change cyrillic A and T to A and T
  docs/pyqgis_developer_cookbook/network_analysis.rst
Labels: backport release_3.10, backport release_3.4

#5314 Do not display "Edit on Github" top message for outdated releases
  conf.py
Labels: backport release_3.10, backport release_3.4

#5357 Fix list formatting on Introducing GIS page
  docs/gentle_gis_introduction/introducing_gis.rst
Labels: backport release_3.10

#5361 Misc tweaks and fixes to server getting started
  docs/user_manual/working_with_ogc/server/getting_started.rst
Labels: backport release_3.10

#4938 3dview properties
  docs/user_manual/working_with_vector/img/3d_view_properties.png
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10

#5373 Mention single and rule-based symbols of 3D rendering
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.10
