Repository qgis/QGIS-Documentation, pull requests merged in 2021-03, with the labels that each got.

#6558 Remove unused setting
  docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.16

#6557 Allow to build pdf files along with html
  .github/workflows/builds.yml
  .github/workflows/html.yml
  README.md
Labels: PDF Docs, backport release_3.16, build/doctest/travis

#6539 Add example to get raster band name
  docs/pyqgis_developer_cookbook/raster.rst
Labels: backport release_3.16

#6538 Add raster contours rendering
  docs/user_manual/working_with_raster/img/rasterContours.png
  docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.16

#6564 Allow to build pdf files along with html (#6557)
  .github/workflows/builds.yml
  .github/workflows/html.yml
  README.md
Labels: PDF Docs, build/doctest/travis

#6572 Add embeddedSymbol to list of renderers
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook

#6391 Add HTML scaling control documentation
  docs/user_manual/print_composer/composer_items/composer_html_frame.rst
Labels: backport release_3.16

#6567 Display :menuselection: arrow in PDF output using unicode format
  conf.py
Labels: PDF Docs, backport release_3.16

#6368 extension open vector options
  docs/user_manual/managing_data_source/img/openoptionsvectorlayer.png
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.16

#6568 Place the images in PDF where they are expected in the rst
  conf.py
Labels: PDF Docs, Screenshots, backport release_3.16

#6580 [TM] Use text to display the render checkbox icon
  docs/training_manual/basic_map/img/toggle_render.png
  docs/training_manual/basic_map/overview.rst
Labels: Training Manual, backport release_3.16

#6555 Do not keep old strings in generated po files
  .github/workflows/pofiles.yml
  scripts/create_transifex_resources.sh
Labels: Translation

#6578 WMS version set to 1.1.1
  docs/server_manual/services.rst
Labels: backport release_3.16

#6587 Swap "select by ..." algorithm method values
  docs/user_manual/processing_algs/qgis/vectorselection.rst
Labels: backport release_3.16

#6586 Parallel jobs to decrease docs builds time
  .github/workflows/builds.yml
Labels: Backend, backport release_3.16, build/doctest/travis

#6594 Fix variables list table column name
  docs/user_manual/working_with_vector/functions_list.rst
Labels: backport release_3.16

#6593 Fix typo
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: Code, backport release_3.16

#6597 Address saving only selected objects in package layers algorithm
  docs/user_manual/processing_algs/qgis/database.rst
Labels: Processing Alg

#6600 Add pygment and line numbers to code blocks
  docs/user_manual/processing/console.rst
Labels: Code, backport release_3.16

#6380 new chapter for vector tiles
  docs/user_manual/index.rst
  docs/user_manual/working_with_vector_tiles/img/vector_tiles_pyramid_structure.png
  docs/user_manual/working_with_vector_tiles/vector_tiles_properties.rst
Labels: backport release_3.16

#6608 small typo
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.16

#6617 Update Logging information
  docs/server_manual/config.rst
Labels: Server, backport release_3.16

#6616 Remove DISPLAY parameter from Apache qgis.demo.conf
  docs/server_manual/getting_started.rst
Labels: Server, backport release_3.16

#6624 Run PO files update workflow only on upstream repo
  .github/workflows/pofiles.yml
Labels: Backend

#6621 Various tweaks and details to the Processing dialog description
  docs/user_manual/processing/toolbox.rst
Labels: Processing, backport release_3.16

#6585 Update extent parameters behavior in Processing GUI
  docs/user_manual/processing/img/extent.png
  docs/user_manual/processing/img/extent_drag.png
  docs/user_manual/processing/img/extent_list.png
  docs/user_manual/processing/toolbox.rst
Labels: backport release_3.16

#6261 Update git.rst
  docs/developers_guide/git.rst
Labels: Developer Manual
