Repository qgis/QGIS-Documentation, pull requests merged in 2022-04, with the labels that each got.

#7457 Mention network connections used in QGIS projects
  docs/user_manual/appendices/index.rst
  docs/user_manual/appendices/qgis_desktop_network_connections.rst
Labels: 3.22

#7451 Display correct version of docs
  docs/index.rst
Labels: 3.22

#7458 Update contributors.rst
  docs/user_manual/preamble/contributors.rst
Labels: backport release_3.22

#7442 Fixing Simplified Chinese build (take 2)
  docker-world.sh
  docs_conf.yml
Labels: Translation, build/doctest

#7460 Update mesh_properties.rst
  docs/user_manual/working_with_mesh/mesh_properties.rst
Labels: Mesh, backport release_3.22

#7445 More pythonic code
  docs/pyqgis_developer_cookbook/vector.rst
Labels: PyQGIS Cookbook, backport release_3.22

#7466 Capital C instead of lower case
  docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Labels: backport release_3.22

#7470 Missing letter "t"
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.22

#7464 Typo's
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.22

#7473 Missing dot and colon
  docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.22

#7475 Typo's
  docs/user_manual/working_with_raster/raster_properties.rst
Labels: backport release_3.22

#7484 Mention Animated symbol marker
  docs/pyqgis_developer_cookbook/vector.rst
Labels: build/doctest

#7492 Broken link fix
  docs/developers_guide/qtcreator.rst
Labels: backport release_3.22

#7488 Edit in place missing checkboxes and text
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: backport release_3.22

#7494 Introduce github branch update instructions
  docs/documentation_guidelines/first_contribution.rst
Labels: backport release_3.22

#7501 Vector Overlay Edit in Place Updates
  docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Labels: backport release_3.22

#7495 Separate the supported_languages list with space instead of comma
  conf.py
  docs_conf.yml
Labels: Backend, Feedback, 3.22

#7496 Fix supported languages list display
  conf.py
  docs_conf.yml
Labels: Backend

#7511 Remove unwanted options from server conf file
  docs/server_manual/getting_started.rst
Labels: Server, backport release_3.22

#7354 Update label's "Edit rule" dialog
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: Labels, backport release_3.22

#6863 Add GPS related algorithms
  docs/user_manual/processing_algs/qgis/gps.rst
  docs/user_manual/processing_algs/qgis/index.rst
Labels: Processing Alg, review_requested, GPS, backport release_3.22

#7518 Replace "WFS3" with "OAPIF"
  docs/server_manual/services/ogcapif.rst
  docs/user_manual/working_with_ogc/ogc_client_support.rst
Labels: Server, Web Service, backport release_3.22

#7522 Add QGIS_SERVER_LANDING_PAGE_PREFIX env variable
  docs/server_manual/config.rst
Labels: Server, backport release_3.22

#7520 Make the Server "getting started" section on Linux more step-through
  docs/server_manual/getting_started.rst
Labels: Server, backport release_3.22

#7527 Add "Show in Files" and Update some browser functions
  docs/user_manual/introduction/browser.rst
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.22
