Repository qgis/QGIS-Documentation, pull requests merged in 2022-03, with the labels that each got.

#7371 [Training manual] Update sampling points exercise
  docs/training_manual/forestry/img/gpx_creation.png
  docs/training_manual/forestry/systematic_sampling.rst
Labels: Training Manual, backport release_3.22

#7381 Do not render gif file in PDF output
  docs/user_manual/introduction/qgis_gui.rst
Labels: backport release_3.22

#7377 updated image in raster calculator
  docs/user_manual/working_with_raster/img/raster_calculator.png
  docs/user_manual/working_with_raster/raster_analysis.rst
Labels: Raster, backport release_3.22

#7258 Add Hungarian to conf
  Makefile
  docs_conf.yml
Labels: Translation, 3.16

#7390 Add list of languages to build and display in the bottom left corner
  docs_conf.yml
Labels: Translation, 3.22

#7389 Target 3.22 for automated scripts
  .github/workflows/pofiles.yml
  .github/workflows/translation_statistics.yml
Labels: Backend

#7388 3.16 docs should now be closed
  conf.py
Labels: 3.16

#7393 Add Transifex configuration file
  transifex.yml
Labels: Translation, Backend

#7392 Pick remaining instructions from old conf and readme files
  README.md
  conf.py
  conf.py.old
  readme_old.rst
Labels: Guidelines, backport release_3.22

#7403 Typo prevents proper format
  docs/training_manual/create_vector_data/forms.rst
Labels: backport release_3.22

#7412 Add Ctrl modifier to Offset Curves tool
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: Editing, backport release_3.22

#7394 Remove unnecessary custom scripts and configs to handle translation
  README.md
  scripts/create_transifex_yaml.sh
Labels: Translation, Code, backport release_3.22

#7409 Update and apply the script to clean repo from unused images
  docs/developers_guide/img/breakPoint.jpeg
  docs/developers_guide/img/buildSteps.jpeg
  docs/developers_guide/img/hammer.jpeg
  docs/developers_guide/img/image11.jpeg
  docs/developers_guide/img/image13.jpeg
  docs/developers_guide/img/runConfig.jpeg
  docs/developers_guide/img/runSettings.jpeg
  docs/developers_guide/img/runSettingsTab.jpeg
  docs/developers_guide/qtcreator.rst
  docs/server_manual/img/server_project_services.png
  docs/training_manual/create_vector_data/img/forest_area_example.png
  docs/training_manual/create_vector_data/img/google_search_entry.png
  docs/training_manual/create_vector_data/img/school_layer_edit_mode.png
  docs/training_manual/forestry/img/map_grid.png
  docs/training_manual/processing/img/iterative_model/tables.png
  docs/training_manual/rasters/img/corner_values.png
  docs/training_manual/rasters/img/good_raster.png
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/print_composer/composer_items/img/de/map_draw_grid.png
  docs/user_manual/print_composer/composer_items/img/de/scalebar_fonts.png
  docs/user_manual/working_with_raster/img/de/rasterRenderAndRessampling.png
  docs/user_manual/working_with_vector/img/symbol_data_defined_edit.png
  scripts/clean_unused_images.sh
  static/common/combobox.png
  static/common/comment.png
  static/common/dateedit.png
  static/common/datetimeedit.png
  static/common/edit.png
  static/common/fontcombobox.png
  static/common/frame.png
  static/common/geometry.png
  static/common/grass_region_edit.png
  static/common/grid.png
  static/common/mIconVector.png
  static/common/reset.png
  static/common/sampling.png
  static/common/splash.png
  static/common/transformed.png
Labels: Backend, backport release_3.22

#7419 Remove substitutions whose image does not exist
  substitutions.txt
Labels: Backend, backport release_3.22

#7434 Add OS
  docs/user_manual/appendices/qgis_desktop_network_connections.rst
Labels: backport release_3.22

#7438 Changed menu name
  docs/server_manual/services/wms.rst
Labels: backport release_3.22

#7446 More details on how to declare plugin dependencies
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
Labels: backport release_3.22

#7272 Server plugins - improve the plugin section and mention a CLI helper tool
  docs/server_manual/plugins.rst
Labels: Server, Plugins, backport release_3.22

#7293 MapBox GL Json for vector tile layers
  docs/user_manual/working_with_vector_tiles/vector_tiles_properties.rst
Labels: backport release_3.22

#7453 Typo, added "fields" to sentence
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.22
