Repository qgis/QGIS-Documentation, pull requests merged in 2023-12, with the labels that each got.

#8687 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.28, backport release_3.34

#8692 Identify tool update
  docs/user_manual/introduction/general_tools.rst
  static/common/mActionIdentifyByMouseOver.png
  substitutions.txt
Labels: backport release_3.34

#8682 Update vector geometry algorithms
  docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Labels: Processing Alg, backport release_3.34

#8693 Add note about QGIS server in PG Service section
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.34

#8643 Exploring the Symbology and Labels tabs of vector tiles
  docs/user_manual/working_with_vector_tiles/vector_tiles.rst
Labels: Properties, Vector Tiles, backport release_3.34

#8700 [3.34] Indicate the version in which the align rasters algs were introduced
  docs/index.rst
  docs/user_manual/expressions/expression_help/Map_Layers.rst
  docs/user_manual/grass_integration/grass_integration.rst
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/map_views/map_view.rst
  docs/user_manual/preamble/contributors.rst
  docs/user_manual/processing_algs/qgis/rastertools.rst
Labels: 3.34

#8704 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.28, backport release_3.34

#8708 Save vector feature to file alg update
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: backport release_3.34

#8709 Create a mailmap file for committers
  .mailmap
Labels: Backend

#8662 PyQGIS Developer Cookbook: fix qgis_global_settings.ini file name
  docs/pyqgis_developer_cookbook/settings.rst
Labels: Project/Configuration, backport release_3.34

#8435 Group the Joins and Relations sections in a dedicated chapter
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/working_with_vector/attribute_table.rst
  docs/user_manual/working_with_vector/img/add_airport_airline.png
  docs/user_manual/working_with_vector/img/airport_attributes.png
  docs/user_manual/working_with_vector/img/airport_attributes_expanded.png
  docs/user_manual/working_with_vector/img/airport_relation_dataview.png
  docs/user_manual/working_with_vector/img/airport_relation_formproperties.png
  docs/user_manual/working_with_vector/img/airports_airlines_relation.png
  docs/user_manual/working_with_vector/img/airports_airlines_relation_formproperties.png
  docs/user_manual/working_with_vector/img/polymorphic_relation_properties.png
  docs/user_manual/working_with_vector/img/polymorphic_relations.png
  docs/user_manual/working_with_vector/img/regions_airports_mapping.png
  docs/user_manual/working_with_vector/img/regions_with_airports.png
  docs/user_manual/working_with_vector/index.rst
  docs/user_manual/working_with_vector/joins_relations.rst
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: Project/Configuration, Properties, backport release_3.34

#8727 Substitutions list cleanup running find_set_subst.py script
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/introduction/browser.rst
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/managing_data_source/opening_data.rst
  docs/user_manual/working_with_3d_tiles/3d_tiles.rst
  docs/user_manual/working_with_projections/working_with_projections.rst
  substitutions.txt
Labels: backport release_3.34

#8730 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.28, backport release_3.34

#8721 Measure tool copy settings update
  docs/user_manual/introduction/img/options_map_tools.png
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/map_views/map_view.rst
Labels: Project/Configuration, backport release_3.34

#8723 Load and save buttons added to OGC server connection
  docs/user_manual/working_with_ogc/ogc_client_support.rst
Labels: backport release_3.34

#8736 Mention Load and Save connections buttons closer
  docs/user_manual/working_with_ogc/ogc_client_support.rst
Labels: backport release_3.34
