Repository qgis/QGIS-Documentation, pull requests merged in 2023-04, with the labels that each got.

#8155 Add sensor_data expression function and update geometry functions
  docs/user_manual/expressions/expression_help/GeometryGroup.rst
  docs/user_manual/expressions/expression_help/Sensors.rst
  docs/user_manual/expressions/functions_list.rst
Labels: Expressions

#8156 [3.28] Update expression functions help
  docs/user_manual/expressions/expression_help/GeometryGroup.rst
  docs/user_manual/expressions/expression_help/Operators.rst
  docs/user_manual/expressions/expression_help/Record_and_Attributes.rst
Labels: Expressions, 3.28

#8157 Update scripts to generate .tx/config file formatting
  scripts/create_transifex_resources.sh
Labels: Translation, Backend, Code

#8158 [3.28] Update scripts to generate .tx/config file formatting
  .tx/config
  scripts/create_transifex_resources.sh
Labels: Translation, Backend, Code, 3.28

#8163 Fix Loop checkbox in temporal navigation
  docs/user_manual/map_views/map_view.rst
Labels: backport release_3.28

#8151 Consolidating github actions with best practices
  .github/workflows/auto-label.yml
  .github/workflows/backport.yml
  .github/workflows/builds.yml
  .github/workflows/doctest.yml
  .github/workflows/pofiles.yml
  .github/workflows/pull_minimized_translations.yml
  .github/workflows/stale.yml
  .github/workflows/translation_statistics.yml
Labels: Backend, Code

#8171 A bit of cleanup around transifex urls
  Makefile
  README.md
  conf.py
  docs/index.rst
  docs/pyqgis_developer_cookbook/plugins/plugins.rst
  release_process.md
  scripts/minimize_translation.sh
Labels: Translation, backport release_3.28

#8184 Server - Add the feature display name to the WMS GetFeatureInfo
  docs/server_manual/services/wms.rst
Labels: Server, Web Service

#8183 Use MapServer demo WMS as example answer
  docs/training_manual/online_resources/wms.rst
Labels: Training Manual, backport release_3.28

#8193 Tweak instructions on substitutions addition
  docs/documentation_guidelines/substitutions.rst
Labels: Guidelines, backport release_3.28

#8203 Fixing various substitutions
  docs/documentation_guidelines/substitutions.rst
  docs/server_manual/plugins.rst
  docs/user_manual/print_composer/composer_items/composer_map.rst
  docs/user_manual/working_with_mesh/mesh_properties.rst
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
  substitutions.txt
Labels: backport release_3.28

#8209 Modify logic of stats reports and fix broken action
  .github/workflows/translation_statistics.yml
Labels: Backend

#8215 Use github repo for sample dataset instead of download.qgis.org
  docs/documentation_guidelines/writing.rst
Labels: backport release_3.28

#8222 Update way to reach Transifex pages
  conf.py
  themes/rtd_qgis/versions.html
Labels: Translation, Code, backport release_3.28

#8208 Update add WFS layer dialog and the filtering process
  docs/user_manual/working_with_ogc/ogc_client_support.rst
Labels: Web Service, backport release_3.28

#8162 Add separate example for each type of installation process
  docs/server_manual/getting_started.rst
  docs/server_manual/services/wcs.rst
  docs/server_manual/services/wms.rst
Labels: Server, backport release_3.28
