Repository qgis/QGIS-Documentation, pull requests merged in 2023-03, with the labels that each got.

#7968 Adjust the table of content and fix some texts
  docs/pyqgis_developer_cookbook/server.rst
Labels: PyQGIS Cookbook, Server, REVIEW REQUESTED, backport release_3.28

#8080 Store translation statistics inside substitutions
  docs/user_manual/preamble/translation_stats.rst
  scripts/load_tx_stats.py
Labels: Translation, Code, backport release_3.28

#8087 [TM] Update formatting and instructions in forest_maps exercise
  docs/training_manual/forestry/forest_maps.rst
Labels: Training Manual, backport release_3.28

#8093 Fix inaccuracy in vector layer description
  docs/user_manual/processing/toolbox.rst
Labels: backport release_3.28

#8098 Fix QGIS Server installation Getting Started
  docs/server_manual/getting_started.rst
Labels: backport release_3.22, backport release_3.28

#8091 More mention of 3D features as digitizable
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: Vector, Editing, backport release_3.28

#8106 Add action to automatically pull unfinished translated files twice a month
  .github/workflows/pull_minimized_translations.yml
  README.md
  release_process.md
  scripts/minimize_translation.sh
Labels: Translation, Backend, backport release_3.22, backport release_3.28

#8110 Let's fully depend on QGIS-Website requirements
  REQUIREMENTS.txt
Labels: Backend, build/doctest, backport release_3.28

#8112 tx not found
  .github/workflows/pull_minimized_translations.yml
Labels: Backend

#8119 Replace "File" menu with "Project"
  docs/documentation_guidelines/substitutions.rst
  docs/gentle_gis_introduction/introducing_gis.rst
  docs/training_manual/appendix/preparing_data.rst
  docs/training_manual/basic_map/overview.rst
  docs/training_manual/complete_analysis/analysis_exercise.rst
  docs/training_manual/map_composer/dynamic_layout.rst
  docs/user_manual/print_composer/overview_composer.rst
  docs/user_manual/style_library/symbol_selector.rst
Labels: Text, backport release_3.28

#8125 Remove 2.8 and 2.14 from bottom menu
  docs_conf.yml
  scripts/fix_versions.sh
Labels: backport release_3.22, backport release_3.28

#8130 Simplify the load translation script using functions
  scripts/load_tx_stats.py
Labels: Translation, Code, backport release_3.28

#8129 Add examples of invalid mesh
  docs/user_manual/working_with_mesh/img/invalid_mesh.png
  docs/user_manual/working_with_mesh/mesh_properties.rst
Labels: Showcase/Screenshots, Mesh, backport release_3.28

#8133 Shadow not Mask part of Text
  docs/user_manual/style_library/label_settings.rst
Labels: backport release_3.22, backport release_3.28

#8139 Auto-pull translation statistics to master branch
  .github/workflows/translation_statistics.yml
Labels: Translation, Code, backport release_3.28
