Repository qgis/QGIS-Documentation, pull requests merged in 2024-02, with the labels that each got.

#8818 Add HTML_FI_ONLY_MAPTIP value to GetFeatureInfo WITH_MAPTIP parameter
  docs/server_manual/services/wms.rst
Labels: Server, Web Service, 3.36

#8533 Introduce display tab in raster layer properties
  docs/user_manual/expressions/functions_list.rst
  docs/user_manual/working_with_raster/img/rasterDisplay.png
  docs/user_manual/working_with_raster/raster_properties.rst
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: Raster, Properties, backport release_3.34

#8825 Update layer_cursor_point variable
  docs/user_manual/expressions/functions_list.rst
Labels: Server, 3.36

#8758 Update base image from Bullseye to Bookworm
  docs/server_manual/containerized_deployment.rst
Labels: Server, backport release_3.34

#8753 [GPS] 3 - Complete general GPS Options dialog
  docs/user_manual/introduction/img/options_gps.png
  docs/user_manual/introduction/qgis_configuration.rst
Labels: GPS, backport release_3.34

#8815 Add layer groups in GetLegendGraphic requests
  docs/server_manual/getting_started.rst
  docs/server_manual/img/ows_server_wms.png
  docs/server_manual/img/wms_getlegendgraphic_addlayergroups.png
  docs/server_manual/services/wms.rst
Labels: backport release_3.34

#8832 Move services related screenshots to appropriate relative img folder
  docs/server_manual/services/basics.rst
  docs/server_manual/services/img/getfeaturecount_legend.png
  docs/server_manual/services/img/server_redlining.png
  docs/server_manual/services/img/server_selection_parameter.png
  docs/server_manual/services/img/server_wcs_getcoverage_width_height.png
  docs/server_manual/services/img/server_wfs3_collection.png
  docs/server_manual/services/img/server_wfs3_collections.png
  docs/server_manual/services/img/server_wfs3_feature.png
  docs/server_manual/services/img/server_wfs3_features.png
  docs/server_manual/services/img/server_wfs3_landing_page.png
  docs/server_manual/services/img/set_group_wms_data.png
  docs/server_manual/services/img/wms_getlegendgraphic_addlayergroups.png
  docs/server_manual/services/img/wms_getlegendgraphic_boxspace.png
  docs/server_manual/services/img/wms_getlegendgraphic_iconlabelspace.png
  docs/server_manual/services/img/wms_getlegendgraphic_itemfontbold.png
  docs/server_manual/services/img/wms_getlegendgraphic_itemfontcolor.png
  docs/server_manual/services/img/wms_getlegendgraphic_itemfontitalic.png
  docs/server_manual/services/img/wms_getlegendgraphic_itemfontsize.png
  docs/server_manual/services/img/wms_getlegendgraphic_layerfontbold.png
  docs/server_manual/services/img/wms_getlegendgraphic_layerfontcolor.png
  docs/server_manual/services/img/wms_getlegendgraphic_layerfontitalic.png
  docs/server_manual/services/img/wms_getlegendgraphic_layerfontsize.png
  docs/server_manual/services/img/wms_getlegendgraphic_layerspace.png
  docs/server_manual/services/img/wms_getlegendgraphic_layertitlespace.png
  docs/server_manual/services/img/wms_getlegendgraphic_rulelabel.png
  docs/server_manual/services/img/wms_getlegendgraphic_symbolheight.png
  docs/server_manual/services/img/wms_getlegendgraphic_symbolspace.png
  docs/server_manual/services/img/wms_getlegendgraphic_symbolwidth.png
  docs/server_manual/services/img/wms_getmap_filter.png
  docs/server_manual/services/img/wms_getmap_opacities.png
  docs/server_manual/services/ogcapif.rst
  docs/server_manual/services/wcs.rst
  docs/server_manual/services/wms.rst
Labels: Showcase/Screenshots, backport release_3.34

#8831 Allow automatic backport of dependabot changes to other branches
  .github/dependabot.yml
  release_process.md
Labels: Backend, dependencies, backport release_3.34

#8840 Added explanation of label masking
  docs/user_manual/style_library/label_settings.rst
Labels: Labels, backport release_3.34

#8809 Loading XYZ tiles without creating a connection
  docs/user_manual/managing_data_source/opening_data.rst
Labels: Web Service, backport release_3.34

#8842 Update doc about QGIS_SERVER_PROJECT_CACHE_CHECK_INTERVAL
  docs/server_manual/config.rst
Labels: Server, Web Service, backport release_3.34

#8848 LAYERATTRIBUTES many layers
  docs/server_manual/services/wms.rst
Labels: Server, backport release_3.34

#8854 Correct icon for add line features button
  static/common/mActionCaptureLine.png
Labels: backport release_3.28, backport release_3.34

#8857 Remove unavailable Edit submenus
  docs/user_manual/introduction/qgis_gui.rst
Labels: 3.28

#8846 Edits to clarify Configure Georeferencer settings
  docs/user_manual/working_with_raster/georeferencer.rst
Labels: backport release_3.34

#8790 Sublayer selection checkboxes added
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.34

#8862 Serial sensor baudrate feature
  docs/user_manual/introduction/qgis_configuration.rst
Labels: 3.36

#8804 MS SQL server connection fix
  docs/user_manual/managing_data_source/opening_data.rst
Labels: backport release_3.34

#8795 Field properties (comments and alias) update
  docs/user_manual/introduction/browser.rst
  docs/user_manual/working_with_vector/img/add_field_comments_aliases.png
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: backport release_3.34

#8875 [processing] The "Generate XYZ tiles" algs have been ported to C++
  docs/user_manual/processing_algs/qgis/rastertools.rst
Labels: Processing Alg, backport release_3.34

#8874 Auto-cancel running builds on PRs when pushing a new commit
  .github/workflows/builds.yml
  .github/workflows/doctest.yml
Labels: Backend

#8878 [processing] Fill NoData: remove the NO_MASK parameter (Fix #8871)
  docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Labels: Processing Alg

#8860 Updating the "Identify features" tool
  docs/user_manual/introduction/general_tools.rst
Labels: Tools, backport release_3.34

#8754 [GPS] 4 - Move GPSBabel instructions to loading from GPS devices section
  docs/user_manual/introduction/qgis_configuration.rst
  docs/user_manual/working_with_gps/plugins_gps.rst
Labels: GPS, backport release_3.34

#8886 Update 3d map toolbar and config dialogs
  docs/documentation_guidelines/substitutions.rst
  docs/user_manual/map_views/3d_map_view.rst
  docs/user_manual/map_views/img/3dmapconfiguration_advanced.png
  docs/user_manual/map_views/img/3dmapconfiguration_camera.png
  docs/user_manual/map_views/img/3dmapconfiguration_effects.png
  docs/user_manual/map_views/img/3dmapconfiguration_general.png
  docs/user_manual/map_views/img/3dmapconfiguration_lights.png
  docs/user_manual/map_views/img/3dmapview.png
  static/common/mIconCamera.png
  static/common/mIconShadow.png
  substitutions.txt
Labels: 3D, 3.36

#8835 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.28, backport release_3.34

#8906 Move down the Identify features section in vector attribute table page
  docs/user_manual/working_with_vector/attribute_table.rst
Labels: Tools, backport release_3.34

#8872 Add a message on translation progress at the top of the pages
  conf.py
Labels: Translation, backport release_3.34

#8764 Show raster row/column of clicked point in identify results
  docs/user_manual/working_with_raster/raster_properties.rst
Labels: Tools, backport release_3.34
