Repository qgis/QGIS-Documentation, pull requests merged in 2025-02, with the labels that each got.

#9578 CMYK Properties Widget
  docs/user_manual/introduction/img/project_colors.png
  docs/user_manual/introduction/qgis_configuration.rst
Labels: 3.42

#9611 docs: fix punctuation and spelling in qgis_configuration.rst
  docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.40

#9609 [GH Actions] Add recommended configuration to harden the runner
  .github/workflows/auto-label.yml
  .github/workflows/backport.yml
  .github/workflows/builds.yml
  .github/workflows/doctest.yml
  .github/workflows/pofiles.yml
  .github/workflows/pull_minimized_translations.yml
  .github/workflows/stale.yml
  .github/workflows/translation_statistics.yml
Labels: Backend, backport release_3.40

#9605 Add a button at the top of the pages to reach the "Get involved" page
  themes/rtd_qgis/breadcrumbs.html
  themes/rtd_qgis/static/css/qgis_docs.css
Labels: backport release_3.34, backport release_3.40

#9589 Mesh dataset group remove button
  docs/user_manual/working_with_mesh/img/mesh_source.png
  docs/user_manual/working_with_mesh/mesh.rst
Labels: 3.42

#9572 Tweak table of stored style components
  docs/user_manual/introduction/general_tools.rst
  docs/user_manual/introduction/img/style_combobox.png
Labels: Properties, backport release_3.40

#9568 Add a section about the symbol's extent buffer
  docs/user_manual/working_with_vector/img/extent_buffer.gif
  docs/user_manual/working_with_vector/vector_properties.rst
Labels: 3.42

#9619 Add link to Elevation Controller section
  docs/user_manual/introduction/qgis_configuration.rst
Labels: backport release_3.40

#9618 [GH Actions] Add recommended configuration to harden the runner
  .github/workflows/auto-label.yml
  .github/workflows/backport.yml
  .github/workflows/builds.yml
  .github/workflows/doctest.yml
  .github/workflows/pofiles.yml
  .github/workflows/pull_minimized_translations.yml
  .github/workflows/stale.yml
  .github/workflows/translation_statistics.yml
Labels: 3.40

#9624 Make strings in the themes folder also translatable
  .github/workflows/pofiles.yml
  conf.py
  scripts/create_transifex_resources.sh
  themes/rtd_qgis/breadcrumbs.html
  themes/rtd_qgis/layout.html
Labels: Translation, Backend, backport release_3.40

#9625 [3.34] Make strings in the themes folder also translatable
  .github/workflows/pofiles.yml
  .tx/config
  conf.py
  locale/en/LC_MESSAGES/sphinx.po
  scripts/create_transifex_resources.sh
  themes/rtd_qgis/breadcrumbs.html
  themes/rtd_qgis/layout.html
Labels: Translation, 3.34

#9629 Update po files also when template files are updated
  .github/workflows/pofiles.yml
Labels: Translation, backport release_3.34, backport release_3.40

#9632 Fix Hyperlink formatting
  docs/developers_guide/codingstandards.rst
Labels: backport release_3.40

#9639 Fix typo
  docs/user_manual/style_library/label_settings.rst
Labels: backport release_3.40

#9582 Advanced Digitizing - Construction Guides
  docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Labels: Vector, Editing, backport release_3.40

#9648 Fix spelling in map_production rst
  docs/gentle_gis_introduction/map_production.rst
Labels: backport release_3.40

#9645 Update parameter in SpatiaLite Execute SQL algorithm
  docs/user_manual/processing_algs/qgis/database.rst
Labels: Processing Alg, backport release_3.40

#9636 Clarify cartographic placement for labels using DD button
  docs/user_manual/style_library/label_settings.rst
Labels: Labels, backport release_3.40

#9654 Update label_settings.rst - definition for Data defined rotation
  docs/user_manual/style_library/label_settings.rst
Labels: Labels, backport release_3.40

#9647 Remove option to define layer name from Add WMS, WFS and delimited text dialogs
  docs/user_manual/managing_data_source/img/delimited_text_dialog.png
  docs/user_manual/managing_data_source/opening_data.rst
  docs/user_manual/working_with_ogc/img/add_connection_wfs.png
  docs/user_manual/working_with_ogc/img/connection_wfs.png
  docs/user_manual/working_with_ogc/img/connection_wms.png
  docs/user_manual/working_with_ogc/ogc_client_support.rst
Labels: 3.42

#9646 Update the GDAL Slope and Proximity algs parameters
  docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Labels: Processing Alg, 3.42

#9576 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.34, backport release_3.40

#9643 Add expression functions to create CRS from string definition and to get CRS authid
  docs/user_manual/expressions/expression_help/CRS.rst
  docs/user_manual/expressions/expression_help/GeometryGroup.rst
  docs/user_manual/expressions/functions_list.rst
Labels: Expressions, 3.42

#9656 Remove features from selection with Cmd-drag on Mac. Also typo fixes.
  docs/user_manual/introduction/general_tools.rst
Labels: backport release_3.40

#9662 Mention array_to_string as alternative for string concatenation functions
  docs/user_manual/expressions/functions_list.rst
Labels: Expressions, backport release_3.40

#9670 Ignore _build folder
  .gitignore
Labels: backport release_3.34, backport release_3.40

#9666 Update statistics of translation
  docs/user_manual/preamble/translation_stats.rst
Labels: Translation, backport release_3.34

#9642 Structure an introductory document for QGIS documentation
  conf.py
  docs/about/contributors.rst
  docs/about/conventions.rst
  docs/about/features.rst
  docs/about/foreword.rst
  docs/about/help_and_support.rst
  docs/about/license/GNU_FDL.rst
  docs/about/license/GNU_GPL.rst
  docs/about/license/index.rst
  docs/about/preamble.rst
  docs/about/translation_stats.rst
  docs/index.rst
  docs/user_manual/appendices/index.rst
  docs/user_manual/index.rst
  redirects.txt
Labels: backport release_3.40

#9665 Add parameter for adding source layer info to "Merge vector layers" algorithm
  docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Labels: Processing Alg, 3.42

#9680 Add missing files to redirect
  redirects.txt
Labels: backport release_3.40

#9682 Update list of 3.40 languages
  Makefile
  docker-world.sh
  docs_conf.yml
Labels: 3.40

#9684 Add configuration file for Transifex
  .tx/config
Labels: 3.40

#9685 Fix text indentation
  docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
Labels: Text, backport release_3.40
